import {spawnSync} from 'node:child_process';import test from 'node:test';import assert from 'node:assert/strict';import{buildHostSnapshot}from'./build.mjs';import{factoryRecipe,factorySeal}from'./recipe.mjs';
const config={region:'ap-southeast-1',sourceBundle:'medium_3_0',runtimeBucket:'private-factory-runtime',architecture:'amd64',revision:'a'.repeat(40),runtimeSha256:'b'.repeat(64),lockSha256:'c'.repeat(64),nodeSha256:'d'.repeat(64),nodeVersion:'22.20.0',dockerVersion:'28.2.2-0ubuntu1',caddyVersion:'2.6.2-5',image:'ghcr.io/fluidworksapp/canopy-workspace@sha256:'+'e'.repeat(64)};
function fixture({mismatch=false,snapshotBad=false,createUncertain=false,foreignSnapshot=false}={}){let instance=null,snapshot=null;const calls=[];let tick=0;return{calls,options:{now:()=>tick++,wait:async()=>{},presign:async(_bucket,key)=>{assert.match(key,/^releases\/[a-f0-9]{40}\/[A-Za-z0-9._-]+\.tar\.gz$/);return'https://private-factory-runtime.s3.ap-southeast-1.amazonaws.com/releases/archive?signature=synthetic';},ssh:async(_name,script)=>JSON.stringify({...config,version:1,revision:mismatch?'f'.repeat(40):config.revision,proof:{docker:true,http:true,sanitized:script===factorySeal,bootFenced:script===factorySeal}}),aws:async(action,input)=>{calls.push({action,input});switch(action){case'create-instances':instance={name:input.instanceNames[0],tags:input.tags,state:{name:'running'}};if(createUncertain)throw Error('uncertain response');return{};case'get-instance':return{instance};case'stop-instance':instance.state.name='stopped';return{};case'create-instance-snapshot':snapshot={name:input.instanceSnapshotName,arn:'arn:aws:lightsail:ap-southeast-1:123456789012:InstanceSnapshot/1234-abcd',tags:foreignSnapshot?[]:input.tags,state:'available',location:{regionName:config.region},fromBundleId:config.sourceBundle,fromBlueprintId:snapshotBad?'unverified':'ubuntu_24_04',fromAttachedDisks:[]};return{};case'get-instance-snapshot':return{instanceSnapshot:snapshot};case'delete-instance-snapshot':snapshot=null;return{};case'delete-instance':instance=null;return{};default:throw Error('Unexpected AWS operation '+action);}}}};}
test('factory only emits a verified catalog after smokes, seal and stopped snapshot; builder always deleted',async()=>{const f=fixture();const record=await buildHostSnapshot(config,f.options);assert.equal(record.entries[0].proof.sanitized,true);assert.equal(record.entries[0].sourceBundle,'medium_3_0');assert.deepEqual(f.calls.filter(c=>['stop-instance','create-instance-snapshot','delete-instance'].includes(c.action)).map(c=>c.action),['stop-instance','create-instance-snapshot','delete-instance']);assert.equal(f.calls.some(c=>c.action==='delete-instance-snapshot'),false);});
test('failed smoke metadata never snapshots and cleans the exact builder',async()=>{const f=fixture({mismatch:true});await assert.rejects(buildHostSnapshot(config,f.options),/metadata/);assert.equal(f.calls.some(c=>c.action==='create-instance-snapshot'),false);assert.equal(f.calls.at(-1).action,'delete-instance');});
test('failed snapshot validation removes its own snapshot and builder without publishing',async()=>{const f=fixture({snapshotBad:true});await assert.rejects(buildHostSnapshot(config,f.options),/not verified/);assert.deepEqual(f.calls.filter(c=>c.action.startsWith('delete-')).map(c=>c.action),['delete-instance-snapshot','delete-instance']);});
test('uncertain creation response still observes and cleans a tagged created builder',async()=>{const f=fixture({createUncertain:true});await assert.rejects(buildHostSnapshot(config,f.options),/uncertain/);assert.equal(f.calls.at(-1).action,'delete-instance');});
test('foreign snapshot cleanup is refused while owned builder is still cleaned',async()=>{const f=fixture({foreignSnapshot:true});await assert.rejects(buildHostSnapshot(config,f.options),/foreign/);assert.equal(f.calls.some(c=>c.action==='delete-instance-snapshot'),false);assert.equal(f.calls.at(-1).action,'delete-instance');});
test('factory recipes require pinned hashes, lock identity, private archive and known public immutable smoke',()=>{for(const patch of [{nodeVersion:'latest'},{runtimeSha256:'bad'},{architecture:'arm64'},{dockerVersion:'docker;curl bad'},{image:'ghcr.io/foreign/image@sha256:'+'e'.repeat(64)}])assert.throws(()=>factoryRecipe({...config,...patch},'https://bucket.s3.amazonaws.com/code'));assert.throws(()=>factoryRecipe(config,'http://bucket.s3.amazonaws.com/code'));const recipe=factoryRecipe(config,'https://bucket.s3.amazonaws.com/code');assert.match(recipe,/sha256sum -c -/);assert.match(recipe,/npm ci --omit=dev --ignore-scripts/);assert.match(recipe,/--network none --read-only --cap-drop ALL/);assert.match(factorySeal,/cloud-init clean --logs --machine-id/);assert.match(factorySeal,/\/etc\/ssh\/ssh_host_/);assert.match(factorySeal,/systemctl disable/);});

test('generated pinned prepare and sanitization scripts parse without executing commands',()=>{for(const script of [factoryRecipe(config,'https://bucket.s3.amazonaws.com/code'),factorySeal]){const parsed=spawnSync('bash',['-n'],{input:script,encoding:'utf8'});assert.equal(parsed.status,0,parsed.stderr);}});

test('an explicit immutable hotfix archive is used without overwriting or changing the base revision',async()=>{const f=fixture(),key=`releases/${config.revision}/workspace-host-startup-reliability-20261006.tar.gz`;let requested;const presign=f.options.presign;f.options.presign=async(bucket,value)=>{requested=value;return presign(bucket,value);};const catalog=await buildHostSnapshot({...config,runtimeKey:key},f.options);assert.equal(requested,key);assert.equal(catalog.entries[0].revision,config.revision);});
test('an invalid factory archive key fails before signing or creating resources',async()=>{for(const key of [`releases/${'f'.repeat(40)}/workspace-host.tar.gz`,`releases/${config.revision}/../workspace-host.tar.gz`]){const f=fixture();f.options.presign=async()=>{throw Error('Must not sign an invalid archive');};await assert.rejects(buildHostSnapshot({...config,runtimeKey:key},f.options),/exact private release/);assert.equal(f.calls.length,0);}});
