import {execFile,spawn} from 'node:child_process';import{promisify}from'node:util';import{mkdtemp,readFile,writeFile,rm}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{isIP}from'node:net';import{buildHostSnapshot}from'./build.mjs';
const exec=promisify(execFile);
if(process.argv[2]!=='--execute'||!process.argv[3]||!process.argv[4])throw Error('Usage: node scripts/host-factory/cli.mjs --execute reviewed-config.json ready-catalog.json. This creates temporary billable factory compute, then deletes it.');
const config=JSON.parse(await readFile(process.argv[3],'utf8')),scratch=await mkdtemp(join(tmpdir(),'canopy-host-factory-'));
async function aws(action,input){const file=join(scratch,'request.json');await writeFile(file,JSON.stringify(input),{mode:0o600});try{const result=await exec('aws',['lightsail',action,'--region',config.region,'--cli-input-json','file://'+file,'--output','json'],{timeout:60000,maxBuffer:4*1024*1024});return JSON.parse(result.stdout);}catch(error){if(['get-instance','get-instance-snapshot'].includes(action)&&/NotFoundException/.test(String(error.stderr??'')))return action==='get-instance'?{instance:null}:{instanceSnapshot:null};throw Error('Factory AWS operation failed: '+action);}finally{await rm(file,{force:true});}}
async function ssh(instance,script){const {accessDetails:a}=await aws('get-instance-access-details',{instanceName:instance,protocol:'ssh'});if(a?.instanceName!==instance||a?.protocol!=='ssh'||!isIP(a.ipAddress)||!/^\w[\w-]*$/.test(a.username??'')||!a.privateKey||!a.certKey||!Array.isArray(a.hostKeys)||!a.hostKeys.length)throw Error('Factory SSH identity is unavailable');
 const key=join(scratch,'ssh-key'),cert=key+'-cert.pub',known=join(scratch,'known-hosts');await writeFile(key,a.privateKey,{mode:0o600});await writeFile(cert,a.certKey,{mode:0o600});
 const hosts=a.hostKeys.filter(k=>/^ssh-(?:rsa|ed25519)$|^ecdsa-sha2-nistp(?:256|384|521)$/.test(k.algorithm??'')&&typeof k.publicKey==='string'&&!/[\r\n]/.test(k.publicKey)).map(k=>`${a.ipAddress} ${k.publicKey.startsWith(k.algorithm+' ')?k.publicKey:k.algorithm+' '+k.publicKey}`).join('\n');if(!hosts)throw Error('No provider-verified SSH host key');await writeFile(known,hosts+'\n',{mode:0o600});
 try{return await new Promise((resolve,reject)=>{const child=spawn('ssh',['-i',key,'-o','CertificateFile='+cert,'-o','UserKnownHostsFile='+known,'-o','StrictHostKeyChecking=yes','-o','BatchMode=yes','-o','ConnectTimeout=10',a.username+'@'+a.ipAddress,'sudo bash -s'],{stdio:['pipe','pipe','pipe']});let output='';const timer=setTimeout(()=>{child.kill('SIGKILL');reject(Error('Factory SSH timeout'));},60000);child.stdout.on('data',chunk=>{output+=chunk;if(output.length>1048576)child.kill('SIGKILL');});child.stderr.resume();child.once('error',()=>{clearTimeout(timer);reject(Error('Factory SSH failed'));});child.once('close',code=>{clearTimeout(timer);code===0?resolve(output):reject(Error('Factory SSH failed'));});child.stdin.end(script+'\n');});}finally{await Promise.all([key,cert,known].map(path=>rm(path,{force:true})));}}
try{const catalog=await buildHostSnapshot(config,{aws,ssh,presign:async(bucket,key)=>{const {stdout}=await exec('aws',['s3','presign','s3://'+bucket+'/'+key,'--region',config.runtimeRegion??config.region,'--expires-in','3600'],{timeout:30000,maxBuffer:8192});return stdout.trim();}});await writeFile(process.argv[4],JSON.stringify(catalog,null,2)+'\n',{mode:0o600});process.stdout.write('Verified management snapshot catalog written. Factory compute deleted.\n');}finally{await rm(scratch,{recursive:true,force:true});}
