import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,mkdir,copyFile,readFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {spawnSync} from 'node:child_process';import {createHash} from 'node:crypto';
test('packaging binds actual lock and both Linux gates while excluding retained factory proof and node_modules',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'canopy-package-proof-'));
 try{
  const source=join(dir,'runtime');await mkdir(source);await copyFile(new URL('./package-host-release.sh',import.meta.url),join(source,'package-host-release.sh'));await copyFile(new URL('./runtime-package-integrity.mjs',import.meta.url),join(source,'runtime-package-integrity.mjs'));await copyFile(new URL('./service-release.mjs',import.meta.url),join(source,'service-release.mjs'));
  const pkg={name:'fixture-runtime',version:'1.0.0',dependencies:{example:'1.0.0'}},lock={name:pkg.name,version:pkg.version,lockfileVersion:3,packages:{'':pkg}};
  await writeFile(join(source,'package.json'),JSON.stringify(pkg));await writeFile(join(source,'package-lock.json'),JSON.stringify(lock));
  for(const file of ['install.sh','install-service.sh','canopy-service.service','canopy-service.tmpfiles.conf','network-isolation.sh','agents.lock.json','canopy-host.service','canopy-network.service','canopy-runtime.tmpfiles.conf','safe.mjs','excluded.test.mjs','factory.json'])await writeFile(join(source,file),'synthetic');
  await mkdir(join(source,'node_modules'));await writeFile(join(source,'node_modules','private-fixture'),'never package');
  await mkdir(join(source,'chrome-stream'));for(const file of ['server.mjs','playwright.mjs','protocol.mjs','viewer.html','viewer.js','preview_picker.js'])await writeFile(join(source,'chrome-stream',file),'synthetic');
  const bin=join(dir,'service-bin');await mkdir(bin);const elf=arch=>Buffer.concat([Buffer.from('\x7fELF','latin1'),Buffer.alloc(2048,arch)]);
  const serviceBinaries={};for(const target of ['linux-amd64','linux-arm64']){await writeFile(join(bin,'canopy-serviced-'+target),elf(target));serviceBinaries[target]={sha256:createHash('sha256').update(elf(target)).digest('hex'),bytes:2052};}
  const manifest={runtimeLockSha256:createHash('sha256').update(await readFile(join(source,'package-lock.json'))).digest('hex'),checks:{linuxAmd64:true,linuxArm64:true},serviceBinaries},release=join(dir,'release.json'),archive=join(dir,'runtime.tgz');
  const run=()=>spawnSync('bash',[join(source,'package-host-release.sh'),archive,release,bin],{encoding:'utf8'});
  await writeFile(release,JSON.stringify(manifest));let result=run();assert.equal(result.status,0,result.stderr);const list=spawnSync('tar',['-tzf',archive],{encoding:'utf8'}).stdout;assert.match(list,/safe.mjs/);assert.match(list,/canopy-runtime\.tmpfiles\.conf/,'the runtime ships its own shared-file ownership');for(const name of ['bin/canopy-serviced-linux-amd64','bin/canopy-serviced-linux-arm64','install-service.sh','canopy-service.service','canopy-service.tmpfiles.conf'])assert.ok(list.includes(name),name);assert.doesNotMatch(list,/factory.json|node_modules|excluded.test.mjs/);
  for(const changed of [{...manifest,runtimeLockSha256:'f'.repeat(64)},{...manifest,checks:{linuxAmd64:true,linuxArm64:false}},{...manifest,checks:undefined},{...manifest,serviceBinaries:undefined},{...manifest,serviceBinaries:{'linux-amd64':serviceBinaries['linux-amd64']}},{...manifest,serviceBinaries:{...serviceBinaries,'linux-arm64':{sha256:'0'.repeat(64)}}}]){await writeFile(release,JSON.stringify(changed));assert.notEqual(run().status,0);}
  await writeFile(release,JSON.stringify(manifest));await writeFile(join(bin,'extra'),'x');assert.notEqual(run().status,0,'unexpected files in the binary directory are refused');await rm(join(bin,'extra'));assert.equal(run().status,0);
  await writeFile(release,JSON.stringify(manifest));await writeFile(join(source,'package.json'),JSON.stringify({...pkg,dependencies:{example:'2.0.0'}}));assert.notEqual(run().status,0,'Package-only dependency changes must fail before an archive is emitted');
 }finally{await rm(dir,{recursive:true,force:true});}
});
