import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,writeFile,readFile,readdir,rm,realpath} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,dirname} from 'node:path';import {execFile} from 'node:child_process';import {promisify} from 'node:util';import {copyProjectComponents} from './project-migration.mjs';
const execute=promisify(execFile);
async function fixture(run){
 const root=await realpath(await mkdtemp(join(tmpdir(),'canopy-git-migration-'))),sourceRoot=join(root,'source'),destinationRoot=join(root,'destination');await mkdir(sourceRoot);await mkdir(destinationRoot);const env={PATH:process.env.PATH,HOME:root,GIT_CONFIG_GLOBAL:'/dev/null',GIT_CONFIG_NOSYSTEM:'1',GIT_AUTHOR_NAME:'Synthetic fixture',GIT_AUTHOR_EMAIL:'fixture@example.invalid',GIT_COMMITTER_NAME:'Synthetic fixture',GIT_COMMITTER_EMAIL:'fixture@example.invalid'};
 const git=async(folder,...args)=>(await execute('git',['-c','core.hooksPath=/dev/null','-C',folder,...args],{env})).stdout.trim();
 const init=async folder=>{await mkdir(join(folder,'web'),{recursive:true});await mkdir(join(folder,'api'));await writeFile(join(folder,'web','app.txt'),'synthetic web');await writeFile(join(folder,'api','app.txt'),'synthetic api');await git(folder,'init');await git(folder,'add','.');await git(folder,'commit','-m','Synthetic migration history');};
 try{await run({root,sourceRoot,destinationRoot,git,init});}finally{await rm(root,{recursive:true,force:true});}
}
test('two nested components retain one complete monorepo, Git history and original project grouping',()=>fixture(async f=>{
 const repo=join(f.sourceRoot,'repo');await f.init(repo);const before=await f.git(repo,'rev-parse','HEAD'),originalConfig=await readFile(join(repo,'.git','config'),'utf8');const components=[{id:'web',label:'Web',source:'repo/web',relativePath:'web'},{id:'api',label:'API',source:'repo/api',relativePath:'api'}];
 const migrated=await copyProjectComponents({...f,components});assert.deepEqual(migrated.map(c=>[c.id,c.label]),[['web','Web'],['api','API']]);assert.equal((await readdir(join(f.destinationRoot,'content','.canopy-repositories'))).length,1);
 for(const component of migrated){const folder=join(f.destinationRoot,component.relativePath);assert.equal(await f.git(folder,'rev-parse','HEAD'),before);assert.equal(await f.git(folder,'log','-1','--format=%s'),'Synthetic migration history');assert.equal(await f.git(folder,'status','--porcelain'),'');assert.equal(await f.git(folder,'rev-parse','--show-toplevel'),dirname(folder));}
 assert.equal(await f.git(repo,'rev-parse','HEAD'),before);assert.equal(await readFile(join(repo,'web','app.txt'),'utf8'),'synthetic web');assert.equal(await readFile(join(repo,'.git','config'),'utf8'),originalConfig);
}));
test('worktree metadata fully within project storage is copied and rebound to its new component paths',()=>fixture(async f=>{
 const repo=join(f.sourceRoot,'repo'),worktree=join(f.sourceRoot,'worktree');await f.init(repo);await f.git(repo,'worktree','add','-b','feature',worktree);const migrated=await copyProjectComponents({...f,components:[{id:'web',label:'Web',source:'worktree/web',relativePath:'.'}]});const folder=join(f.destinationRoot,migrated[0].relativePath);
 assert.equal(await f.git(folder,'branch','--show-current'),'feature');assert.equal(await f.git(folder,'log','-1','--format=%s'),'Synthetic migration history');assert.equal(await f.git(folder,'status','--porcelain'),'');assert.equal(await f.git(folder,'rev-parse','--show-toplevel'),dirname(folder));
}));
test('worktree Git directories outside project storage fail clearly before copying and preserve all originals',()=>fixture(async f=>{
 const repo=join(f.root,'outside-storage'),worktree=join(f.sourceRoot,'worktree');await f.init(repo);await f.git(repo,'worktree','add','-b','feature',worktree);const marker=await readFile(join(worktree,'.git'),'utf8');await writeFile(join(f.root,'private-credential-sentinel'),'synthetic private data');
 await assert.rejects(copyProjectComponents({...f,components:[{id:'web',label:'Web',source:'worktree/web',relativePath:'.'}]}),/Git worktree metadata leaves project storage/);assert.deepEqual(await readdir(f.destinationRoot),[]);assert.equal(await readFile(join(worktree,'.git'),'utf8'),marker);assert.equal(await readFile(join(f.root,'private-credential-sentinel'),'utf8'),'synthetic private data');
}));
async function gitMetadataText(folder){let output='';for(const entry of await readdir(folder,{withFileTypes:true})){if(['objects','logs','refs'].includes(entry.name))continue;const file=join(folder,entry.name);if(entry.isDirectory())output+=await gitMetadataText(file);else if(entry.isFile())output+=await readFile(file,'utf8');}return output;}
test('personal Git migration removes known authentication from destination configs and includes without changing originals or author/history',()=>fixture(async f=>{
 const repo=join(f.sourceRoot,'repo');await f.init(repo);const token='SYNTHETIC_OWNER_PAT_DO_NOT_COPY',config=join(repo,'.git','config'),included=join(repo,'.git','auth.cfg'),worktreeConfig=join(repo,'.git','config.worktree');
 await writeFile(config,(await readFile(config,'utf8'))+`\n# ${token}\n[remote "origin"]\n url = https://owner:${token}@github.com/example/repository.git?token=${token}\n pushurl = https://${token}@github.com/example/repository.git\n[credential]\n helper = !echo ${token}\n[http]\n extraheader = Authorization: Bearer ${token}\n[http "https://owner:${token}@github.com/"]\n postBuffer = 1000\n[core]\n sshCommand = ssh -i /home/owner/private-key-${token}\n[user]\n name = Synthetic repository author\n email = author@example.invalid\n[include]\n path = auth.cfg\n[url "https://${token}@github.com/"]\n insteadOf = https://github.com/\n`);
 await writeFile(included,`[credential "https://github.com"]\n helper = store --file=/home/owner/${token}\n[user]\n name = Synthetic repository author\n`);await writeFile(worktreeConfig,`[http]\n extraHeader = Authorization: Bearer ${token}\n`);const original=await readFile(config,'utf8'),before=await f.git(repo,'rev-parse','HEAD');
 const migrated=await copyProjectComponents({...f,components:[{id:'web',label:'Web',source:'repo/web',relativePath:'.'}]});const folder=join(f.destinationRoot,migrated[0].relativePath),gitDir=join(dirname(folder),'.git');
 assert.ok(!(await gitMetadataText(gitDir)).includes(token));assert.equal(await f.git(folder,'remote','get-url','origin'),'https://github.com/example/repository.git');assert.equal(await f.git(folder,'config','user.name'),'Synthetic repository author');assert.equal(await f.git(folder,'config','user.email'),'author@example.invalid');assert.equal(await f.git(folder,'rev-parse','HEAD'),before);assert.equal(await f.git(folder,'status','--porcelain'),'');assert.equal(await readFile(config,'utf8'),original);assert.ok((await readFile(included,'utf8')).includes(token));assert.ok((await readFile(worktreeConfig,'utf8')).includes(token));
}));
test('copied linked-worktree common and per-worktree authentication configs are sanitized',()=>fixture(async f=>{
 const repo=join(f.sourceRoot,'repo'),worktree=join(f.sourceRoot,'worktree');await f.init(repo);await f.git(repo,'worktree','add','-b','feature',worktree);const token='SYNTHETIC_LINKED_WORKTREE_PAT',commonConfig=join(repo,'.git','config');await writeFile(commonConfig,(await readFile(commonConfig,'utf8'))+`\n[credential]\n helper = !echo ${token}\n`);const gitDir=await f.git(worktree,'rev-parse','--absolute-git-dir');await writeFile(join(gitDir,'config.worktree'),`[http]\n extraheader = Authorization: Bearer ${token}\n`);
 const migrated=await copyProjectComponents({...f,components:[{id:'web',label:'Web',source:'worktree/web',relativePath:'.'}]});assert.ok(!(await gitMetadataText(join(f.destinationRoot,'content'))).includes(token));const folder=join(f.destinationRoot,migrated[0].relativePath);assert.equal(await f.git(folder,'branch','--show-current'),'feature');assert.equal(await f.git(folder,'status','--porcelain'),'');assert.ok((await readFile(commonConfig,'utf8')).includes(token));
}));
test('external includes and embedded authentication references fail before copying and never read owner home',()=>fixture(async f=>{
 const repo=join(f.sourceRoot,'repo');await f.init(repo);const config=join(repo,'.git','config'),original=await readFile(config,'utf8'),privateFile=join(f.root,'private-auth.cfg');await writeFile(privateFile,'[credential]\n helper = SYNTHETIC_PRIVATE_PAT\n');
 for(const suffix of [`\n[include]\n path = ${privateFile}\n`,`\n[alias]\n sync = push https://owner:SYNTHETIC_PRIVATE_PAT@github.com/repo\n`]){await writeFile(config,original+suffix);await assert.rejects(copyProjectComponents({...f,components:[{id:'web',label:'Web',source:'repo/web',relativePath:'.'}]}),/External Git configuration includes|authentication reference/);assert.deepEqual(await readdir(f.destinationRoot),[]);assert.equal(await readFile(config,'utf8'),original+suffix);}
 assert.equal(await readFile(privateFile,'utf8'),'[credential]\n helper = SYNTHETIC_PRIVATE_PAT\n');
}));
test('destination excludes local hooks, reflogs and referenced credential stores while preserving source, objects and refs',()=>fixture(async f=>{
 const repo=join(f.sourceRoot,'repo');await f.init(repo);const token='SYNTHETIC_LOCAL_METADATA_PAT',config=join(repo,'.git','config'),store=join(repo,'.git','private-stores','custom-store'),hook=join(repo,'.git','hooks','pre-commit'),log=join(repo,'.git','logs','HEAD'),knownStore=join(repo,'.git','.git-credentials');await mkdir(dirname(store));
 await writeFile(store,`https://owner:${token}@github.com\n`);await writeFile(knownStore,`https://owner:${token}@github.com\n`);await writeFile(hook,`#!/bin/sh\necho ${token}\n`);await writeFile(log,(await readFile(log,'utf8'))+`fetch https://owner:${token}@github.com/example/repository\n`);await writeFile(config,(await readFile(config,'utf8'))+'\n[credential]\n helper = store --file=.git/private-stores/custom-store\n');await writeFile(join(repo,'project-hook.sh'),'explicit shared working-tree code');const before=await f.git(repo,'rev-parse','HEAD'),sourceLog=await readFile(log,'utf8');
 const migrated=await copyProjectComponents({...f,components:[{id:'web',label:'Web',source:'repo/web',relativePath:'.'}]}),folder=join(f.destinationRoot,migrated[0].relativePath),copiedRepo=dirname(folder),gitDir=join(copiedRepo,'.git');assert.ok(!(await gitMetadataText(gitDir)).includes(token));
 for(const relative of ['hooks/pre-commit','logs/HEAD','private-stores/custom-store','.git-credentials'])await assert.rejects(readFile(join(gitDir,relative)),{code:'ENOENT'});assert.equal(await f.git(folder,'rev-parse','HEAD'),before);assert.equal(await f.git(folder,'log','-1','--format=%s'),'Synthetic migration history');assert.equal(await readFile(join(copiedRepo,'project-hook.sh'),'utf8'),'explicit shared working-tree code');assert.ok((await readFile(store,'utf8')).includes(token));assert.ok((await readFile(hook,'utf8')).includes(token));assert.equal(await readFile(log,'utf8'),sourceLog);
}));
test('canonical SSH and SCP remotes retain their SSH identity while passwords and auth queries are removed',()=>fixture(async f=>{
 const repo=join(f.sourceRoot,'repo');await f.init(repo);const config=join(repo,'.git','config'),token='SYNTHETIC_SSH_PASSWORD';await writeFile(config,(await readFile(config,'utf8'))+`\n[remote "ssh"]\n url = ssh://git:${token}@github.com/example/repository.git?token=${token}\n[remote "scp"]\n url = git@github.com:example/repository.git\n`);const original=await readFile(config,'utf8');
 const migrated=await copyProjectComponents({...f,components:[{id:'web',label:'Web',source:'repo/web',relativePath:'.'}]}),folder=join(f.destinationRoot,migrated[0].relativePath);assert.equal(await f.git(folder,'remote','get-url','ssh'),'ssh://git@github.com/example/repository.git');assert.equal(await f.git(folder,'remote','get-url','scp'),'git@github.com:example/repository.git');assert.ok(!(await gitMetadataText(join(dirname(folder),'.git'))).includes(token));assert.equal(await readFile(config,'utf8'),original);
}));
