import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import {once} from 'node:events';import {providerQuotaHeaders} from './provider-quota-headers.mjs';import {CredentialBroker} from './credential-broker.mjs';import {createAgentCliProxy} from './agent-cli-proxy.mjs';
test('quota metadata admits only exact safe numeric fields and rejects account/credential/credit headers',()=>{
 const headers=new Headers({'x-codex-primary-used-percent':'12.5','x-codex-primary-window-minutes':'300','x-codex-primary-reset-at':'1789309000','x-codex-secondary-used-percent':'100','x-codex-secondary-window-minutes':'10080','x-codex-secondary-reset-at':'1789409000','x-codex-credits-balance':'provider-key','x-codex-user-id':'private-user','chatgpt-account-id':'private-account','authorization':'Bearer private'});
 assert.equal(Object.keys(providerQuotaHeaders(headers)).length,6);
 for(const value of ['NaN','Infinity','provider-secret','-1','100.1','1e5','123456789012345678901']){headers.set('x-codex-primary-used-percent',value);assert.equal(providerQuotaHeaders(headers)['x-codex-primary-used-percent'],undefined);}
 headers.set('x-codex-primary-window-minutes','12.5');assert.equal(providerQuotaHeaders(headers)['x-codex-primary-window-minutes'],undefined);
});
test('Codex quota headers survive broker and facade while provider keys and identifiers remain stripped',async()=>{
 const secret='s'.repeat(43),metadata={'x-codex-primary-used-percent':'42','x-codex-secondary-used-percent':'5','x-codex-primary-window-minutes':'300','x-codex-secondary-window-minutes':'10080','x-codex-primary-reset-at':'1789309000','x-codex-secondary-reset-at':'1789409000'};
 let rejected=false;const broker=new CredentialBroker({authorize:async(p,c)=>({...c,accountId:'shared'}),loadCredential:async(a,c)=>({...c,accountId:a,provider:'openai',token:'provider-key'}),fetchImpl:async()=>new Response(rejected?'provider-key':'data: done\n\n',{status:rejected?429:200,headers:{'content-type':'text/event-stream',...metadata,'x-api-key':'provider-key','chatgpt-account-id':'private-account','x-codex-user-id':'private-user','x-codex-credits-balance':'private-balance'}})});
 const server=createAgentCliProxy({agent:'codex',secret,execute:(operation,body,options)=>broker.execute({workspaceId:'workspace',memberId:'alice'},{projectId:'app',operation,body},options)});server.listen(0,'127.0.0.1');await once(server,'listening');const base='http://127.0.0.1:'+server.address().port;
 try{const response=await fetch(base+'/v1/responses',{method:'POST',headers:{authorization:'Bearer '+secret},body:'{}'});assert.equal(await response.text(),'data: done\n\n');for(const [key,value]of Object.entries(metadata))assert.equal(response.headers.get(key),value);for(const key of ['x-api-key','chatgpt-account-id','x-codex-user-id','x-codex-credits-balance'])assert.equal(response.headers.get(key),null);rejected=true;const error=await fetch(base+'/v1/responses',{method:'POST',headers:{authorization:'Bearer '+secret},body:'{}'});assert.equal(error.status,429);assert.ok(!(await error.text()).includes('provider-key'));assert.equal(error.headers.get('x-codex-primary-used-percent'),'42');}finally{server.closeAllConnections();await new Promise(r=>server.close(r));}
});
