import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,readFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createHmac} from 'node:crypto';import http from 'node:http';import {once} from 'node:events';import {SharingSetup} from './sharing-setup.mjs';
async function fixture(run){
 const directory=await mkdtemp(join(tmpdir(),'sharing-setup-')),configPath=join(directory,'host.json');const id='ws-11111111-1111-4111-8111-111111111111',workspace={id,generation:7,desiredState:'running',sharingCgroupParent:'canopy-test.slice',memoryMiB:1024,cpus:1,accounts:['owner']};
 const config={workspaces:[workspace],managedSession:{key:'synthetic-management-key'.repeat(3),workspaceId:id}};await writeFile(configPath,JSON.stringify(config),{mode:0o600});
 const runtime=http.createServer((req,res)=>res.end('[]'));runtime.listen(0,'127.0.0.1');await once(runtime,'listening');const result={url:`http://127.0.0.1:${runtime.address().port}`,token:'synthetic-runner'};
 const calls=[],host={runtimes:new Map(),migrationCleanupRequired:new Set(),verifyCapacity:async w=>{calls.push(['capacity',w.cgroupParent]);if(!w.cgroupParent)throw Error('Missing capacity');},inspectRuntime:async()=>({Id:'original',Config:{Labels:{'canopy.workspace':id}}}),docker:async args=>{calls.push(args);return {stdout:''};},open:async()=>result};
 const options={config,host,directory:join(directory,'migrations'),configPath,authorizeRuntime:async()=>true,instanceName:'generation-7',networkReady:async()=>{},migrate:async options=>{const next={...workspace,cgroupParent:workspace.sharingCgroupParent,projectMounts:[{id:'app',name:'App',writable:true,components:[{id:'web',label:'Web',relativePath:'content'}]}]};await options.verifyRuntime(result,next);await options.saveConfig({...config,workspaces:[next]});Object.assign(workspace,next);await options.journal.append({phase:'committed'});}};
 try{await run({options,workspace,config,host,calls,configPath});}finally{runtime.closeAllConnections();await new Promise(resolve=>runtime.close(resolve));await rm(directory,{recursive:true,force:true});}
}
test('explicit interruption and valid owner project declarations precede any stop',()=>fixture(async f=>{
 const setup=new SharingSetup(f.options);const projects=[{id:'app',name:'App',components:[{id:'web',label:'Web',source:'repo',relativePath:'.'}]}];
 await assert.rejects(setup.start(f.workspace,{projects}),/Confirm/);await assert.rejects(setup.start(f.workspace,{projects:[{...projects[0],components:[{...projects[0].components[0],source:'../credentials'}]}],confirmInterrupt:true}),/Invalid migration/);assert.equal(f.calls.length,0);
 const started=await setup.start(f.workspace,{projects,confirmInterrupt:true});assert.equal(started.status,'running');await setup.jobs.get(f.workspace.id).promise;
 assert.equal((await setup.status(f.workspace)).status,'ready');assert.ok(f.calls.some(args=>args[0]==='stop'));const saved=JSON.parse(await readFile(f.configPath,'utf8'));assert.equal(saved.workspaces[0].cgroupParent,'canopy-test.slice');assert.equal(saved.workspaces[0].projectMounts[0].id,'app');
}));
test('readiness proof is signed by management and bound to generation, instance, nonce and catalog',()=>fixture(async f=>{
 Object.assign(f.workspace,{cgroupParent:'canopy-test.slice',projectMounts:[{id:'app',name:'App',writable:true,components:[{id:'web',label:'Web',relativePath:'content'}]}]});
 const setup=new SharingSetup({...f.options,now:()=>10000}),input={nonce:'a'.repeat(64),generation:7,instanceName:'generation-7'};
 const {proof,projects}=await setup.attest(f.workspace,input),[payload,signature]=proof.split('.');assert.equal(signature,createHmac('sha256',f.config.managedSession.key).update(payload).digest('base64url'));const claims=JSON.parse(Buffer.from(payload,'base64url'));assert.equal(claims.purpose,'sharing-ready');assert.equal(claims.expiresAt,40000);assert.equal(claims.nonce,input.nonce);assert.equal(claims.workspaceId,f.workspace.id);assert.deepEqual(projects,[{id:'app',name:'App',components:[{id:'web',name:'Web'}]}]);
 for(const changed of [{generation:8},{instanceName:'other'},{nonce:'short'}])await assert.rejects(setup.attest(f.workspace,{...input,...changed}));f.host.migrationCleanupRequired.add(f.workspace.id);await assert.rejects(setup.attest(f.workspace,input));
}));
test('failed migration quarantines access and never claims ready',()=>fixture(async f=>{
 const setup=new SharingSetup({...f.options,migrate:async()=>{throw Error('copy failed');}});await setup.start(f.workspace,{confirmInterrupt:true,projects:[{id:'app',name:'App',components:[{id:'web',label:'Web',source:'repo',relativePath:'.'}]}]});await setup.jobs.get(f.workspace.id).promise;assert.equal((await setup.status(f.workspace)).status,'recovery-required');assert.equal(f.host.migrationCleanupRequired.has(f.workspace.id),true);assert.equal(JSON.parse(await readFile(f.configPath,'utf8')).workspaces[0].projectMounts,undefined);
}));
