import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import {CredentialVault} from './credential-vault.mjs';import {subscriptionCredentialLoader} from './subscription-credentials.mjs';import {CredentialBroker} from './credential-broker.mjs';
const workspaceId='ws-11111111-1111-4111-8111-111111111111',context={workspaceId,memberId:'alice',projectId:'app',operation:'agents:claude'},credential={provider:'anthropic',authType:'oauth',token:'old-access',refreshToken:'old-refresh',expiresAt:1000};
async function fixture(action){const root=await mkdtemp(path.join(tmpdir(),'shared-oauth-'));try{const vault=await CredentialVault.initialize(root);await vault.store(workspaceId,'shared',credential);await action(vault);}finally{await rm(root,{recursive:true,force:true});}}
test('concurrent requests refresh once, persist rotated tokens and keep refresh secrets outside broker responses',()=>fixture(async vault=>{
 let refreshes=0;const loader=subscriptionCredentialLoader(vault,{now:()=>2000,fetchImpl:async(url,options)=>{refreshes++;assert.equal(url,'https://platform.claude.com/v1/oauth/token');assert.equal(options.redirect,'error');const body=JSON.parse(options.body);assert.equal(body.grant_type,'refresh_token');assert.equal(body.refresh_token,'old-refresh');assert.equal(body.client_id,'9d1c250a-e61b-44d9-88ed-5944d1962f5e');return Response.json({access_token:'new-access',refresh_token:'rotated-refresh',expires_in:3600});}});
 const values=await Promise.all([loader('shared',context),loader('shared',context)]);assert.equal(refreshes,1);assert.equal(values[0].token,'new-access');assert.equal(values[1].refreshToken,'rotated-refresh');assert.equal((await vault.load('shared',context)).refreshToken,'rotated-refresh');
 const broker=new CredentialBroker({authorize:async(p,c)=>({...c,accountId:'shared'}),loadCredential:loader,fetchImpl:async(url,options)=>{assert.equal(url,'https://api.anthropic.com/v1/messages');assert.equal(options.headers.authorization,'Bearer new-access');assert.equal(options.headers['x-api-key'],undefined);assert.ok(options.headers['anthropic-beta'].includes('oauth-2025-04-20'));assert.ok(options.headers['anthropic-beta'].includes('capability-2026-10-05'));return Response.json({ok:true});}});
 const response=await broker.execute({workspaceId,memberId:'alice'},{projectId:'app',operation:'agents:claude',body:Buffer.from('{}'),providerHeaders:{'anthropic-beta':'capability-2026-10-05'}});assert.deepEqual(await response.json(),{ok:true});
}));
test('account removal during refresh is serialized and cannot resurrect a deleted shared credential',()=>fixture(async vault=>{
 let entered,release;const started=new Promise(r=>entered=r),gate=new Promise(r=>release=r);
 const loader=subscriptionCredentialLoader(vault,{now:()=>2000,fetchImpl:async()=>{entered();await gate;return Response.json({access_token:'new',refresh_token:'rotated',expires_in:3600});}});
 const load=loader('shared',context);await started;const removal=vault.remove(workspaceId,'shared');release();await Promise.all([load,removal]);await assert.rejects(vault.load('shared',context));
}));
test('Codex subscription refresh uses fixed JSON endpoint/account binding and rejects account switching and forged URLs',()=>fixture(async vault=>{
 await vault.store(workspaceId,'codex',{provider:'openai',authType:'oauth',token:'old',refreshToken:'refresh',expiresAt:1000,providerAccountId:'account-a'});
 const jwt=claims=>'header.'+Buffer.from(JSON.stringify(claims)).toString('base64url')+'.signature';let mismatch=true;
 const loader=subscriptionCredentialLoader(vault,{now:()=>2000,fetchImpl:async(url,options)=>{assert.equal(url,'https://auth.openai.com/oauth/token');assert.equal(JSON.parse(options.body).client_id,'app_EMoamEEZ73f0CkXaXp7hrann');return Response.json({access_token:jwt({exp:3600,'https://api.openai.com/auth':{chatgpt_account_id:mismatch?'account-b':'account-a'}}),refresh_token:'new-refresh'});}});
 await assert.rejects(loader('codex',context),/Subscription sign-in required/);assert.equal((await vault.load('codex',context)).refreshToken,'refresh');mismatch=false;await loader('codex',context);
 const broker=new CredentialBroker({authorize:async(p,c)=>({...c,accountId:'codex'}),loadCredential:loader,fetchImpl:async(url,options)=>{assert.equal(url,'https://chatgpt.com/backend-api/codex/responses');assert.equal(options.headers['chatgpt-account-id'],'account-a');assert.equal(options.headers.originator,'codex_cli_rs');return Response.json({ok:true});}});await (await broker.execute({workspaceId,memberId:'alice'},{projectId:'app',operation:'agents:codex',body:Buffer.from('{}')})).json();
 await assert.rejects(vault.store(workspaceId,'forged',{...credential,refreshUrl:'http://169.254.169.254'}));
}));
test('a hanging forged refresh response cannot hold the vault lock or persist a late result',()=>fixture(async vault=>{
 let resolve;const pending=new Promise(r=>resolve=r);const loader=subscriptionCredentialLoader(vault,{now:()=>2000,timeoutMs:20,fetchImpl:async()=>pending});
 await assert.rejects(loader('shared',context),/Subscription sign-in required/);await vault.remove(workspaceId,'shared');resolve(Response.json({access_token:'late',refresh_token:'late',expires_in:3600}));await new Promise(r=>setTimeout(r,10));await assert.rejects(vault.load('shared',context));
}));
