import {it,expect,vi,beforeEach} from 'vitest';
const mocks=vi.hoisted(()=>({invoke:vi.fn(),guard:vi.fn(()=>true),active:{connection:{workspaceId:'shoaib-work',endpoint:'https://legacy.example'},setProjectIdle:vi.fn()}}));
vi.mock('@tauri-apps/api/core',()=>({invoke:mocks.invoke}));vi.mock('../executionMode',()=>({canSwitchExecutionMode:mocks.guard}));vi.mock('./workspace',()=>({activeWorkspace:()=>mocks.active}));
import {hibernateWorkspaceProjects} from './hibernateWorkspace';
beforeEach(()=>{vi.clearAllMocks();mocks.guard.mockReturnValue(true);mocks.invoke.mockImplementation(async(_command,args)=>args.route==='/api/workspaces'?{workspaces:[{id:'shoaib-work',state:'stopped'}]}:{accepted:true});});
it('snapshots every project before releasing resources and requesting VM shutdown',async()=>{
 const order:string[]=[];mocks.invoke.mockImplementation(async(_command,args)=>{if(args.route==='/api/workspaces')return {workspaces:[{id:'shoaib-work',state:'stopped'}]};order.push('stop');return {accepted:true};});await hibernateWorkspaceProjects(['app','api'],async id=>{order.push('save:'+id);},async id=>{order.push('release:'+id);});expect(order).toEqual(['save:app','save:api','release:app','release:api','stop']);expect(mocks.invoke).toHaveBeenCalledWith('canopy_account_request',expect.objectContaining({body:expect.objectContaining({workspaceId:'shoaib-work',action:'hibernate',confirmInterrupt:true})}));
});
it('snapshot failure prevents VM shutdown and resource release',async()=>{
 const release=vi.fn();await expect(hibernateWorkspaceProjects(['app','api'],async id=>{if(id==='api')throw Error('disk full');},release)).rejects.toThrow('disk full');expect(release).not.toHaveBeenCalled();expect(mocks.invoke).not.toHaveBeenCalled();
});
it('unsaved edits block hibernation before any snapshot or shutdown',async()=>{
 mocks.guard.mockReturnValue(false);const snapshot=vi.fn();await expect(hibernateWorkspaceProjects(['app'],snapshot,vi.fn())).rejects.toThrow('Save unsaved');expect(snapshot).not.toHaveBeenCalled();expect(mocks.invoke).not.toHaveBeenCalled();
});
it('keeps the project UI mounted and reports a refused shutdown',async()=>{
 mocks.invoke.mockResolvedValue({accepted:false});await expect(hibernateWorkspaceProjects([],vi.fn(),vi.fn())).rejects.toThrow('may still be running');
});

it('does not stop when projects change during snapshotting',async()=>{const release=vi.fn();await expect(hibernateWorkspaceProjects(['app'],vi.fn(),release,()=>false)).rejects.toThrow('Projects changed');expect(release).not.toHaveBeenCalled();expect(mocks.invoke).not.toHaveBeenCalled();});
it('does not treat accepted shutdown as confirmed compute shutdown',async()=>{mocks.invoke.mockImplementation(async(_command,args)=>args.route==='/api/workspaces'?{workspaces:[{id:'shoaib-work',state:'error'}]}:{accepted:true});await expect(hibernateWorkspaceProjects([],vi.fn(),vi.fn())).rejects.toThrow('Could not confirm');});
it('publishes actual saved-project counts and confirms completed only after external stopped state',async()=>{const progress:unknown[]=[];await hibernateWorkspaceProjects(['app','api'],async()=>{},async()=>{},()=>true,value=>progress.push(value));expect(progress).toEqual([{phase:'saving-projects',savedProjects:0,totalProjects:2,shutdownAccepted:false},{phase:'saving-projects',savedProjects:1,totalProjects:2,shutdownAccepted:false},{phase:'saving-projects',savedProjects:2,totalProjects:2,shutdownAccepted:false},{phase:'stopping-services',savedProjects:2,totalProjects:2,shutdownAccepted:false},{phase:'stopping-compute',savedProjects:2,totalProjects:2,shutdownAccepted:false},{phase:'stopping-compute',savedProjects:2,totalProjects:2,shutdownAccepted:true},{phase:'stopping-compute',savedProjects:2,totalProjects:2,shutdownAccepted:true},{phase:'completed',savedProjects:2,totalProjects:2,shutdownAccepted:true}]);});
it('recovers a hung remote release only when durable snapshots and external stopped state are confirmed',async()=>{vi.useFakeTimers();try{const snapshot=vi.fn(async()=>{}),progress=vi.fn();const result=hibernateWorkspaceProjects(['app'],snapshot,()=>new Promise(()=>{}),()=>true,progress);await vi.advanceTimersByTimeAsync(8000);await result;expect(snapshot).toHaveBeenCalledOnce();expect(progress).toHaveBeenLastCalledWith({phase:'completed',savedProjects:1,totalProjects:1,shutdownAccepted:true});expect(mocks.invoke.mock.calls.some(([,args])=>args.body?.action==='hibernate')).toBe(false);}finally{vi.useRealTimers();}});
it('retrying shutdown only observes and advances the existing intent, never issues a new hibernate',async()=>{const {waitForWorkspaceStopped}=await import('./hibernateWorkspace');const listener=vi.fn();await waitForWorkspaceStopped('shoaib-work',listener);expect(mocks.invoke).toHaveBeenCalledOnce();expect(mocks.invoke).toHaveBeenCalledWith('canopy_account_request',{route:'/api/workspaces',body:null});expect(listener).toHaveBeenLastCalledWith({phase:'completed',shutdownAccepted:true});});
