import {it,expect,vi,beforeEach} from 'vitest';
const mocks=vi.hoisted(()=>({invoke:vi.fn(),lifecycle:vi.fn(),guard:vi.fn(()=>true),active:{connection:{workspaceId:'shoaib-work',endpoint:'https://legacy.example'},setProjectIdle:vi.fn()}}));
vi.mock('@tauri-apps/api/core',()=>({invoke:mocks.invoke}));vi.mock('../executionMode',()=>({canSwitchExecutionMode:mocks.guard}));vi.mock('./workspace',()=>({activeWorkspace:()=>mocks.active}));vi.mock('./connectionState',()=>({connectionKey:(endpoint:string,id:string)=>`${endpoint}/${id}`,reportWorkspaceLifecycle:mocks.lifecycle}));
import {hibernateWorkspaceProjects} from './hibernateWorkspace';
beforeEach(()=>{vi.clearAllMocks();mocks.active={connection:{workspaceId:'shoaib-work',endpoint:'https://legacy.example'},setProjectIdle:vi.fn()};mocks.guard.mockReturnValue(true);mocks.invoke.mockImplementation(async(_command,args)=>args.route==='/api/workspaces'?{workspaces:[{id:'shoaib-work',state:'stopped'}]}:{accepted:true});});
it('snapshots every project before releasing resources and requesting VM shutdown',async()=>{
 const order:string[]=[];mocks.invoke.mockImplementation(async(_command,args)=>{if(args.route==='/api/workspaces')return {workspaces:[{id:'shoaib-work',state:'stopped'}]};order.push('stop');return {accepted:true};});await hibernateWorkspaceProjects(['app','api'],async id=>{order.push('save:'+id);},async id=>{order.push('release:'+id);});expect(order).toEqual(['save:app','save:api','release:app','release:api','stop']);expect(mocks.invoke).toHaveBeenCalledWith('canopy_account_request',expect.objectContaining({body:expect.objectContaining({workspaceId:'shoaib-work',action:'hibernate',confirmInterrupt:true})}));
});
it('snapshot failure prevents VM shutdown and resource release',async()=>{
 const release=vi.fn();await expect(hibernateWorkspaceProjects(['app','api'],async id=>{if(id==='api')throw Error('disk full');},release)).rejects.toThrow('disk full');expect(release).not.toHaveBeenCalled();expect(mocks.invoke).not.toHaveBeenCalled();
});
it('unsaved edits block hibernation before any snapshot or shutdown',async()=>{
 mocks.guard.mockReturnValue(false);const snapshot=vi.fn();await expect(hibernateWorkspaceProjects(['app'],snapshot,vi.fn())).rejects.toThrow('Save unsaved');expect(snapshot).not.toHaveBeenCalled();expect(mocks.invoke).not.toHaveBeenCalled();
});
it('keeps the project UI mounted and reports a refused shutdown',async()=>{
 mocks.invoke.mockResolvedValue({accepted:false});await expect(hibernateWorkspaceProjects([],vi.fn(),vi.fn())).rejects.toThrow('may still be running');
});

it('does not stop when projects change during snapshotting',async()=>{const release=vi.fn();await expect(hibernateWorkspaceProjects(['app'],vi.fn(),release,()=>false)).rejects.toThrow('Projects changed');expect(release).not.toHaveBeenCalled();expect(mocks.invoke).not.toHaveBeenCalled();});
it('does not treat accepted shutdown as confirmed compute shutdown',async()=>{mocks.invoke.mockImplementation(async(_command,args)=>args.route==='/api/workspaces'?{workspaces:[{id:'shoaib-work',state:'error'}]}:{accepted:true});await expect(hibernateWorkspaceProjects([],vi.fn(),vi.fn())).rejects.toThrow('Could not confirm');});
it('publishes actual saved-project counts and confirms completed only after external stopped state',async()=>{const progress:unknown[]=[];await hibernateWorkspaceProjects(['app','api'],async()=>{},async()=>{},()=>true,value=>progress.push(value));expect(progress).toEqual([{phase:'saving-projects',savedProjects:0,totalProjects:2,shutdownAccepted:false},{phase:'saving-projects',savedProjects:1,totalProjects:2,shutdownAccepted:false},{phase:'saving-projects',savedProjects:2,totalProjects:2,shutdownAccepted:false},{phase:'stopping-services',savedProjects:2,totalProjects:2,shutdownAccepted:false},{phase:'stopping-compute',savedProjects:2,totalProjects:2,shutdownAccepted:false},{phase:'stopping-compute',savedProjects:2,totalProjects:2,shutdownAccepted:true},{phase:'stopping-compute',savedProjects:2,totalProjects:2,shutdownAccepted:true},{phase:'completed',savedProjects:2,totalProjects:2,shutdownAccepted:true}]);});
it('recovers a hung remote release only when durable snapshots and external stopped state are confirmed',async()=>{vi.useFakeTimers();try{const snapshot=vi.fn(async()=>{}),progress=vi.fn();const result=hibernateWorkspaceProjects(['app'],snapshot,()=>new Promise(()=>{}),()=>true,progress);await vi.advanceTimersByTimeAsync(8000);await result;expect(snapshot).toHaveBeenCalledOnce();expect(progress).toHaveBeenLastCalledWith({phase:'completed',savedProjects:1,totalProjects:1,shutdownAccepted:true});expect(mocks.invoke.mock.calls.some(([,args])=>args.body?.action==='hibernate')).toBe(false);}finally{vi.useRealTimers();}});
it('retrying shutdown only observes and advances the existing intent, never issues a new hibernate',async()=>{const {waitForWorkspaceStopped}=await import('./hibernateWorkspace');const listener=vi.fn();await waitForWorkspaceStopped('shoaib-work',listener);expect(mocks.invoke).toHaveBeenCalledOnce();expect(mocks.invoke).toHaveBeenCalledWith('canopy_account_request',{route:'/api/workspaces',body:{action:'status',id:'shoaib-work'}});expect(listener).toHaveBeenLastCalledWith({phase:'completed',shutdownAccepted:true});});

const managedId='ws-11111111-1111-1111-1111-111111111111';
function managed(){mocks.active.connection={workspaceId:managedId,endpoint:`https://${managedId}.workspaces.canopyide.dev`};}
it('observes a durably accepted shutdown after its POST response times out without another shutdown request',async()=>{vi.useFakeTimers();try{
 managed();let reads=0;const progress=vi.fn();mocks.invoke.mockImplementation((_command,args)=>{if(args.body?.action==='hibernate')return new Promise(()=>{});if(args.body?.action==='advance')return Promise.resolve({});reads++;return Promise.resolve({workspaces:[{id:managedId,state:reads===1?'stopping':'stopped',operation:{id:'11111111-1111-1111-1111-111111111111',action:'hibernate',status:reads===1?'running':'succeeded',phase:'retaining-storage'}}]});});
 const result=hibernateWorkspaceProjects([],vi.fn(),vi.fn(),()=>true,progress);await vi.advanceTimersByTimeAsync(8000);expect(progress).toHaveBeenLastCalledWith(expect.objectContaining({shutdownAccepted:true,phase:'stopping-compute'}));await vi.advanceTimersByTimeAsync(2000);await result;
 expect(progress).toHaveBeenLastCalledWith(expect.objectContaining({shutdownAccepted:true,phase:'completed'}));expect(mocks.lifecycle).toHaveBeenCalledWith(`${mocks.active.connection.endpoint}/${managedId}`,'stopping');expect(mocks.lifecycle).toHaveBeenLastCalledWith(`${mocks.active.connection.endpoint}/${managedId}`,'hibernated');const shutdowns=mocks.invoke.mock.calls.filter(([,args])=>args.body?.action==='hibernate');expect(shutdowns).toHaveLength(1);expect(shutdowns[0][1].body.requestKey).toMatch(/^[a-f0-9-]{36}$/);expect(mocks.invoke.mock.calls.every(([,args])=>!['resume','retry','connect'].includes(args.body?.action))).toBe(true);expect(mocks.invoke.mock.calls.filter(([,args])=>args.route==='/api/workspaces').every(([,args])=>args.body?.id===managedId&&args.body.action==='status')).toBe(true);
 }finally{vi.useRealTimers();}});
it('tolerates bounded status and advance response delays while observing the same accepted intent',async()=>{vi.useFakeTimers();try{
 managed();let reads=0,advances=0;mocks.invoke.mockImplementation((_command,args)=>{if(args.body?.action==='hibernate')return Promise.resolve({accepted:true});if(args.body?.action==='advance'){advances++;return new Promise(()=>{});}reads++;if(reads===1)return new Promise(()=>{});return Promise.resolve({workspaces:[{id:managedId,state:reads===2?'stopping':'stopped',operation:{id:'11111111-1111-1111-1111-111111111111',action:'hibernate',status:'running'}}]});});
 const result=hibernateWorkspaceProjects([],vi.fn(),vi.fn());await vi.advanceTimersByTimeAsync(20000);await result;expect(advances).toBe(1);expect(reads).toBe(3);expect(mocks.invoke.mock.calls.filter(([,args])=>args.body?.action==='hibernate')).toHaveLength(1);
 }finally{vi.useRealTimers();}});
it('allows an initially ambiguous ready observation to settle without resubmitting',async()=>{vi.useFakeTimers();try{managed();let reads=0;mocks.invoke.mockImplementation((_command,args)=>args.body?.action==='hibernate'?new Promise(()=>{}):Promise.resolve({workspaces:[{id:managedId,state:++reads===1?'ready':'stopped'}]}));const result=hibernateWorkspaceProjects([],vi.fn(),vi.fn());await vi.advanceTimersByTimeAsync(10000);await result;expect(reads).toBe(2);expect(mocks.invoke.mock.calls.filter(([,args])=>args.body?.action==='hibernate')).toHaveLength(1);}finally{vi.useRealTimers();}});
it('retains the overall 120-second deadline even when every status response is lost',async()=>{vi.useFakeTimers();try{managed();mocks.invoke.mockImplementation((_command,args)=>args.body?.action==='hibernate'?Promise.resolve({accepted:true}):new Promise(()=>{}));const result=hibernateWorkspaceProjects([],vi.fn(),vi.fn());const rejection=expect(result).rejects.toThrow('taking longer than expected');await vi.advanceTimersByTimeAsync(120000);await rejection;expect(mocks.invoke.mock.calls.filter(([,args])=>args.body?.action==='hibernate')).toHaveLength(1);}finally{vi.useRealTimers();}});
it('does not swallow permission denial as a transient status failure',async()=>{mocks.invoke.mockImplementation(async(_command,args)=>{if(args.body?.action==='hibernate')return{accepted:true};throw Error('403 Forbidden');});await expect(hibernateWorkspaceProjects([],vi.fn(),vi.fn())).rejects.toThrow('403 Forbidden');});
it('does not report stopped if another active action has replaced shutdown',async()=>{const {waitForWorkspaceStopped}=await import('./hibernateWorkspace');mocks.invoke.mockResolvedValue({workspaces:[{id:'shoaib-work',state:'stopped',operation:{action:'resume',status:'pending'}}]});await expect(waitForWorkspaceStopped('shoaib-work')).rejects.toThrow('replaced this shutdown');});
it('does not advance or mark completion for an account changed while status is pending',async()=>{vi.useFakeTimers();try{managed();let resolveStatus!:(value:unknown)=>void;const progress=vi.fn();mocks.invoke.mockImplementation((_command,args)=>args.body?.action==='hibernate'?Promise.resolve({accepted:true}):new Promise(resolve=>{resolveStatus=resolve;}));const result=hibernateWorkspaceProjects([],vi.fn(),vi.fn(),()=>true,progress);const rejection=expect(result).rejects.toThrow('Account or workspace changed');await vi.advanceTimersByTimeAsync(0);window.dispatchEvent(new Event('canopy:account-changed'));resolveStatus({workspaces:[{id:managedId,state:'stopped'}]});await rejection;expect(progress).not.toHaveBeenLastCalledWith(expect.objectContaining({phase:'completed'}));expect(mocks.invoke.mock.calls.some(([,args])=>args.body?.action==='advance')).toBe(false);}finally{vi.useRealTimers();}});

it('checking an existing stopped shutdown updates the active header lifecycle without a new request',async()=>{const {waitForWorkspaceStopped}=await import('./hibernateWorkspace');const progress=vi.fn();await waitForWorkspaceStopped('shoaib-work',progress);expect(mocks.lifecycle).toHaveBeenLastCalledWith('https://legacy.example/shoaib-work','hibernated');expect(progress).toHaveBeenLastCalledWith({phase:'completed',shutdownAccepted:true});expect(mocks.invoke.mock.calls.some(([,args])=>args.body?.action==='hibernate')).toBe(false);});
it('changing the active workspace during observation cannot complete or advance the old shutdown',async()=>{vi.useFakeTimers();try{managed();let resolveStatus!:(value:unknown)=>void;mocks.invoke.mockImplementation((_command,args)=>args.body?.action==='hibernate'?Promise.resolve({accepted:true}):new Promise(resolve=>{resolveStatus=resolve;}));const result=hibernateWorkspaceProjects([],vi.fn(),vi.fn());const rejection=expect(result).rejects.toThrow('Account or workspace changed');await vi.advanceTimersByTimeAsync(0);mocks.active={connection:{workspaceId:'another',endpoint:'https://another.example'},setProjectIdle:vi.fn()};resolveStatus({workspaces:[{id:managedId,state:'stopped'}]});await rejection;expect(mocks.lifecycle).not.toHaveBeenCalledWith(expect.anything(),'hibernated');expect(mocks.invoke.mock.calls.some(([,args])=>args.body?.action==='advance')).toBe(false);}finally{vi.useRealTimers();}});

it('without an observed shutdown operation id, status checks cannot advance an unrelated future operation',async()=>{vi.useFakeTimers();try{managed();let reads=0;mocks.invoke.mockImplementation(async(_command,args)=>args.body?.action==='hibernate'?{accepted:true}:{workspaces:[{id:managedId,state:++reads===1?'stopping':'stopped',operation:{action:'hibernate',status:'running'}}]});const result=hibernateWorkspaceProjects([],vi.fn(),vi.fn());await vi.advanceTimersByTimeAsync(2000);await result;expect(mocks.invoke.mock.calls.some(([,args])=>args.body?.action==='advance')).toBe(false);}finally{vi.useRealTimers();}});

it('an accepted operation receipt cannot advance a different later hibernate intent',async()=>{managed();mocks.invoke.mockImplementation(async(_command,args)=>args.body?.action==='hibernate'?{accepted:true,operation:{id:'11111111-1111-1111-1111-111111111111'}}:{workspaces:[{id:managedId,state:'stopping',operation:{id:'22222222-2222-2222-2222-222222222222',action:'hibernate',status:'running'}}]});await expect(hibernateWorkspaceProjects([],vi.fn(),vi.fn())).rejects.toThrow('replaced this shutdown');expect(mocks.invoke.mock.calls.some(([,args])=>args.body?.action==='advance')).toBe(false);});
it('waits through a long snapshot-storage save and reports its phases instead of timing out after two minutes',async()=>{vi.useFakeTimers();try{
 const {waitForWorkspaceStopped}=await import('./hibernateWorkspace');managed();let reads=0;const progress=vi.fn();
 const opId='11111111-2222-4333-8444-555555555555';
 mocks.invoke.mockImplementation(async(_command,args)=>{if(args.body?.action==='advance')return {};reads++;const done=reads>120;return {workspaces:[{id:managedId,state:done?'stopped':'stopping',storage_mode:'snapshot',operation:done?{id:opId,action:'hibernate',status:'succeeded',phase:'complete'}:{id:opId,action:'hibernate',status:'running',phase:reads<5?'saving-workspace':'saving-snapshot',save_progress:'30%'}}]};});
 const result=waitForWorkspaceStopped(managedId,progress);
 await vi.advanceTimersByTimeAsync(5*60*1000);await result;
 expect(progress).toHaveBeenCalledWith(expect.objectContaining({phase:'stopping-compute',savePhase:'saving-workspace'}));
 expect(progress).toHaveBeenCalledWith(expect.objectContaining({phase:'stopping-compute',savePhase:'saving-snapshot',saveProgress:'30%'}));
 expect(progress).toHaveBeenLastCalledWith({phase:'completed',shutdownAccepted:true});
}finally{vi.useRealTimers();}});
