import {useEffect,useState} from 'react';
import {Button} from '../components/ui';
import type {HibernateProgress} from './hibernateWorkspace';
import './workspaceHibernateProgress.css';
import {savePhaseLabel} from './storageStatus';
export type HibernateOperation={workspaceId:string;name:string;progress:HibernateProgress;startedAt:number;error?:string};
const stages=[{phase:'saving-projects',label:'Save projects',description:'Save open projects and session snapshots.'},{phase:'stopping-services',label:'Stop services',description:'Close terminals, agents and project services.'},{phase:'stopping-compute',label:'Stop compute',description:'Wait for the cloud service to confirm shutdown.'}] as const;
export function WorkspaceHibernateProgress({operation,minimized,onMinimize,onExpand,onRetry,onDismiss}:{operation:HibernateOperation;minimized:boolean;onMinimize:()=>void;onExpand:()=>void;onRetry:()=>void;onDismiss:()=>void}){
 const [elapsed,setElapsed]=useState(()=>Math.floor((Date.now()-operation.startedAt)/1000));
 useEffect(()=>{const timer=setInterval(()=>setElapsed(Math.floor((Date.now()-operation.startedAt)/1000)),1000);return()=>clearInterval(timer);},[operation.startedAt]);
 const completed=operation.progress.phase==='completed',index=completed?3:stages.findIndex(stage=>stage.phase===operation.progress.phase);
 const title=completed?'Workspace hibernated':operation.error?'Hibernation needs attention':`Hibernating ${operation.name}`;
 const saving=!completed&&operation.progress.phase==='stopping-compute'?savePhaseLabel(operation.progress.savePhase,operation.progress.saveProgress):null;
 const current=completed?'Compute is stopped':saving??stages[index]?.label??'Saving projects';
 return <aside className={`workspace-hibernate-progress${minimized?' minimized':''}${operation.error?' failed':''}`} aria-label="Workspace hibernation progress"><header><span className="workspace-hibernate-mark" aria-hidden="true">{completed?'✓':operation.error?'!':'❄'}</span><div><strong>{minimized?operation.name:title}</strong><span role="status">{operation.error?'Needs attention':current}</span>{!minimized&&<small className="workspace-hibernate-elapsed">{elapsed}s elapsed</small>}</div>{minimized?<Button icon variant="ghost" aria-label="Expand hibernation progress" onClick={onExpand}>＋</Button>:<Button icon variant="ghost" aria-label="Minimize hibernation progress" onClick={onMinimize}>−</Button>}</header>{!minimized&&<><ol>{stages.map((stage,step)=><li key={stage.phase} className={step<index?'done':step===index?'active':'pending'}><span aria-hidden="true">{step<index?'✓':step+1}</span><div><strong>{stage.label}</strong><small>{step===index&&stage.phase==='saving-projects'&&operation.progress.totalProjects!==undefined?`${operation.progress.savedProjects??0} of ${operation.progress.totalProjects} projects saved`:step===index&&stage.phase==='stopping-compute'&&saving?saving:stage.description}</small></div></li>)}</ol>{operation.error?<p className="workspace-hibernate-error" role="alert">{operation.error}</p>:<p className="workspace-hibernate-note">{completed?'Your projects and files are saved. Wake the workspace when you are ready to continue.':operation.progress.shutdownAccepted?'Shutdown is accepted. You can keep working locally while compute stops.':'Keep working locally while Canopy saves and closes this workspace.'}</p>}<footer>{operation.error&&<Button size="sm" variant="accent" onClick={onRetry}>{operation.progress.phase==='stopping-compute'?'Check shutdown':'Retry hibernation'}</Button>}{completed||operation.error?<Button size="sm" onClick={onDismiss}>Dismiss</Button>:<Button size="sm" onClick={onMinimize}>Continue working</Button>}</footer></>}</aside>;
}
