import {afterEach,it,expect,vi} from 'vitest';
import {act,cleanup,fireEvent,render,screen,within} from '@testing-library/react';
const mocks=vi.hoisted(()=>({invoke:vi.fn(),switchMode:vi.fn(),open:vi.fn()}));
vi.mock('@tauri-apps/api/core',()=>({invoke:mocks.invoke}));
vi.mock('../executionMode',()=>({canSwitchExecutionMode:()=>true,setExecutionMode:mocks.switchMode}));
vi.mock('./workspace',()=>({activeWorkspace:()=>null}));
vi.mock('./client',()=>({RemoteExecutionClient:class{workspace=mocks.open;}}));
vi.mock('../components/AccountSettings',()=>({AccountSettings:()=>null}));
vi.mock('../components/WorkspaceSharing',()=>({WorkspaceSharing:()=>null}));
vi.mock('../components/SharedSessionsPanel',()=>({SharedSessionsPanel:()=>null}));
vi.mock('./WorkspaceOwnerTools',()=>({WorkspaceOwnerTools:()=>null}));
vi.mock('./LocalProjectImport',()=>({LocalProjectImport:()=>null}));
vi.mock('./RemoteDesktop',()=>({RemoteDesktop:()=>null}));
import {WorkspaceSelector} from './WorkspaceSelector';
afterEach(()=>{cleanup();vi.useRealTimers();vi.clearAllMocks();window.dispatchEvent(new Event('canopy:account-changed'));});
it('keeps Local selected through reordered polls and pins a background startup to its own workspace',async()=>{
 vi.useFakeTimers();let starting=false,reversed=false;
 const machine=()=>({id:'ws-machine',name:'Machine Works',provider:'lightsail',state:starting?'starting':'stopped',cpu_max:4,memory_max_mib:32768,operation:{phase:'preparing-workspace'}});
 const shoaib={id:'ws-shoaib',name:'Shoaib workspace',provider:'lightsail',state:'stopped',cpu_max:4,memory_max_mib:32768};
 mocks.invoke.mockImplementation(async(command,args)=>{
  if(command==='execution_remote_list')return [{id:'legacy-one',workspaceId:'ws-shoaib',endpoint:'https://old.example',workspaceName:'Shoaib workspace'},{id:'legacy-two',workspaceId:'ws-shoaib',endpoint:'https://ws-shoaib.workspaces.canopyide.dev',workspaceName:'Shoaib workspace'}];
  if(command==='canopy_account_cache_key')return null;
  if(command==='canopy_account_request'&&args.route==='/api/workspaces')return {workspaces:reversed?[shoaib,machine()]:[machine(),shoaib]};
  if(command==='canopy_account_request'&&args.body?.action==='resume')starting=true;
  return {};
 });
 render(<WorkspaceSelector onboarding/>);await act(async()=>{});
 expect(screen.getAllByRole('tab',{name:'Shoaib workspace'})).toHaveLength(1);
 const initialTabs=screen.getAllByRole('tab').map(tab=>tab.textContent);
 expect(screen.getByRole('tab',{name:/^Local workspace/})).toHaveAttribute('aria-selected','true');
 fireEvent.click(screen.getByRole('tab',{name:'Machine Works'}));
 fireEvent.click(screen.getByRole('button',{name:'Resume workspace'}));await act(async()=>{});
 expect(screen.getByLabelText('Workspace startup')).toHaveTextContent('Machine Works');
 fireEvent.click(screen.getByRole('tab',{name:/^Local workspace/}));
 expect(screen.queryByLabelText('Workspace startup')).toBeNull();
 expect(screen.getByLabelText('Workspace progress')).toHaveTextContent('Machine Works');
 expect(screen.getByText(/Projects, agent sign-ins and Git settings use this Mac/)).toBeInTheDocument();
 reversed=true;await act(async()=>{await vi.advanceTimersByTimeAsync(10000);});
 expect(screen.getByRole('tab',{name:/^Local workspace/})).toHaveAttribute('aria-selected','true');
 expect(screen.getAllByRole('tab').map(tab=>tab.textContent)).toEqual(initialTabs);
 expect(screen.queryByLabelText('Workspace startup')).toBeNull();
 fireEvent.click(screen.getByRole('tab',{name:'Shoaib workspace'}));
 expect(screen.queryByLabelText('Workspace startup')).toBeNull();
 expect(screen.getByRole('heading',{name:'Shoaib workspace'})).toBeInTheDocument();
 fireEvent.click(within(screen.getByLabelText('Workspace progress')).getByRole('button',{name:'Details'}));
 expect(screen.getByRole('tab',{name:'Machine Works'})).toHaveAttribute('aria-selected','true');
 expect(screen.getByLabelText('Workspace startup')).toHaveTextContent('Machine Works');
 expect(mocks.switchMode).not.toHaveBeenCalled();
});
