import {useEffect,useRef,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {Button,TextInput} from './ui';
import './organizationSettings.css';
type Organization={id:string;name:string;role:string};
type Person={id:string;name:string;email:string;role:string};
type Team={id:string;name:string;members?:Person[]};
type Invitation={id:string;name:string};
type Detail={invitations?:{id:string;email:string;expires_at:string}[];members:Person[];teams:Team[];role:string};
const request=<T,>(body:unknown)=>invoke<T>('canopy_account_request',{route:'/api/teams',body});
export function OrganizationSettings(){
 const [organizations,setOrganizations]=useState<Organization[]>([]),[invitations,setInvitations]=useState<Invitation[]>([]),[selected,setSelected]=useState('');
 const [detail,setDetail]=useState<Detail|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 const [name,setName]=useState(''),[teamName,setTeamName]=useState(''),[email,setEmail]=useState(''),[team,setTeam]=useState(''),[person,setPerson]=useState('');
 const [creating,setCreating]=useState(false),[removing,setRemoving]=useState<Person|null>(null);
 const [removingFromTeam,setRemovingFromTeam]=useState<{team:Team;person:Person}|null>(null);
 const generation=useRef(0),accountEpoch=useRef(0);
 async function list(){const epoch=accountEpoch.current;const data=await request<{organizations:Organization[];invitations:Invitation[]}>({action:'organization-list'});if(epoch!==accountEpoch.current)return;setOrganizations(data.organizations);setInvitations(data.invitations);setSelected(current=>data.organizations.some(o=>o.id===current)?current:data.organizations[0]?.id??'');}
 useEffect(()=>{const refresh=()=>{const epoch=accountEpoch.current;void list().catch(e=>{if(epoch===accountEpoch.current)setError(String(e));}).finally(()=>{if(epoch===accountEpoch.current)setLoading(false);});};const changed=()=>{accountEpoch.current++;generation.current++;setOrganizations([]);setInvitations([]);setSelected('');setDetail(null);setRemoving(null);setRemovingFromTeam(null);setError('');setNotice('');setName('');setEmail('');setTeamName('');setBusy(false);setLoading(true);refresh();};window.addEventListener('canopy:account-changed',changed);refresh();return()=>{accountEpoch.current++;generation.current++;window.removeEventListener('canopy:account-changed',changed);};},[]);
 async function load(id:string){const current=++generation.current;setDetail(null);if(!id)return;try{const value=await request<Detail>({action:'organization-detail',organizationId:id});if(current===generation.current)setDetail(value);}catch(e){if(current===generation.current)setError(String(e));}}
 useEffect(()=>{setTeam('');setPerson('');setRemoving(null);setRemovingFromTeam(null);void load(selected);return()=>{generation.current++;};},[selected]);
 async function mutate(body:Record<string,unknown>){if(busy)return false;const epoch=accountEpoch.current;setBusy(true);setError('');setNotice('');try{const result=await request<{emailSent?:boolean}>({...body,organizationId:selected||undefined});if(epoch!==accountEpoch.current)return false;await list();if(epoch!==accountEpoch.current)return false;if(selected)await load(selected);if(epoch!==accountEpoch.current)return false;setNotice(result.emailSent===false?'Invitation saved, but email delivery failed. They can accept it after signing in.':'Saved.');return true;}catch(e){if(epoch===accountEpoch.current)setError(String(e));return false;}finally{if(epoch===accountEpoch.current)setBusy(false);}}
 const canManage=detail&&detail.role!=='member';
 return <section className="organization-settings" aria-label="Organization settings">
  <header><div><h2>People & teams</h2><p>Group your people. Share workspaces with the right teams.</p></div><Button size="sm" onClick={()=>setCreating(v=>!v)}>New organization</Button></header>
  {error&&<p className="organization-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
  {invitations.map(i=><div className="organization-row" key={i.id}><span><strong>{i.name}</strong><small>Organization invitation</small></span><Button disabled={busy} onClick={()=>void mutate({action:'organization-accept',invitationId:i.id})}>Accept invitation</Button></div>)}
  {(creating||(!loading&&!organizations.length))&&<form onSubmit={e=>{e.preventDefault();void mutate({action:'organization-create',name}).then(ok=>{if(ok){setName('');setCreating(false);}});}}><label>Organization name<TextInput value={name} onChange={e=>setName(e.target.value)} maxLength={80} placeholder="Your company or group"/></label><Button type="submit" disabled={busy||!name.trim()}>Create organization</Button></form>}
  {loading&&<p role="status">Loading organizations…</p>}
  {!!organizations.length&&<label className="organization-select">Organization<select value={selected} onChange={e=>setSelected(e.target.value)} disabled={busy}>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>}
  {selected&&!detail&&!error&&<p role="status">Loading people and teams…</p>}
  {detail&&<>
   <div className="organization-section-title"><h3>People</h3><span>{detail.members.length} members</span></div>
   {canManage&&<form onSubmit={e=>{e.preventDefault();void mutate({action:'organization-invite',email}).then(ok=>{if(ok)setEmail('');});}}><label>Email address<TextInput type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@company.com"/></label><Button type="submit" disabled={busy||!email.trim()}>Invite person</Button></form>}
   {canManage&&!!detail.invitations?.length&&<div className="organization-invitations"><h4>Pending invitations</h4>{detail.invitations.map(i=><div className="organization-row" key={i.id}><span className="organization-person"><strong>{i.email}</strong><small>Expires {new Date(i.expires_at).toLocaleDateString()}</small></span><Button size="sm" disabled={busy} onClick={()=>void mutate({action:'organization-invitation-revoke',invitationId:i.id})}>Withdraw invitation</Button></div>)}</div>}
   <div>{detail.members.map(m=><div className="organization-row" key={m.id}><span className="organization-avatar" aria-hidden="true">{m.name.slice(0,1).toUpperCase()}</span><span className="organization-person"><strong>{m.name}</strong><small>{m.email}</small></span><span className="organization-role">{m.role}</span>{canManage&&m.role!=='owner'&&(detail.role==='owner'||m.role==='member')&&<Button size="sm" disabled={busy} onClick={()=>setRemoving(m)}>Remove</Button>}</div>)}</div>
   {removing&&<div className="organization-confirm" role="alert"><strong>Remove {removing.name}?</strong><p>They will lose access through this organization and its teams.</p><Button disabled={busy} onClick={()=>void mutate({action:'organization-member-remove',userId:removing.id}).then(ok=>{if(ok)setRemoving(null);})}>Remove member</Button><Button disabled={busy} onClick={()=>setRemoving(null)}>Cancel</Button></div>}
   <div className="organization-section-title"><h3>Teams</h3><span>{detail.teams.length} teams</span></div>
   {canManage&&<form onSubmit={e=>{e.preventDefault();void mutate({action:'organization-team-create',name:teamName}).then(ok=>{if(ok)setTeamName('');});}}><label>Team name<TextInput value={teamName} onChange={e=>setTeamName(e.target.value)} maxLength={80} placeholder="e.g. Engineering"/></label><Button type="submit" disabled={busy||!teamName.trim()}>Create team</Button></form>}
   {!detail.teams.length&&<p className="organization-empty">Create a team to group people who work together.</p>}
   {detail.teams.map(t=><details className="organization-team" key={t.id}><summary><strong>{t.name}</strong><span>{t.members?.length??0} members</span></summary><div>{!t.members?.length&&<p>No members yet. Add people below.</p>}{t.members?.map(m=><div className="organization-row" key={m.id}><span className="organization-avatar" aria-hidden="true">{m.name.slice(0,1).toUpperCase()}</span><span className="organization-person"><strong>{m.name}</strong><small>{m.email}</small></span><span className="organization-role">{m.role}</span>{canManage&&m.role!=='owner'&&<Button size="sm" disabled={busy} aria-label={`Remove ${m.name} from ${t.name}`} onClick={()=>setRemovingFromTeam({team:t,person:m})}>Remove from team</Button>}</div>)}</div></details>)}
   {removingFromTeam&&<div className="organization-confirm" role="alert"><strong>Remove {removingFromTeam.person.name} from {removingFromTeam.team.name}?</strong><p>They will lose this team's chat and workspace access. Access granted directly or through another team stays in place.</p><Button disabled={busy} onClick={()=>void mutate({action:'organization-team-member-remove',teamId:removingFromTeam.team.id,userId:removingFromTeam.person.id}).then(ok=>{if(ok)setRemovingFromTeam(null);})}>Confirm removal</Button><Button disabled={busy} onClick={()=>setRemovingFromTeam(null)}>Cancel</Button></div>}
   {canManage&&!!detail.teams.length&&<form onSubmit={e=>{e.preventDefault();void mutate({action:'organization-team-member-add',teamId:team,userId:person});}}><label>Person<select value={person} onChange={e=>setPerson(e.target.value)}><option value="">Choose a person</option>{detail.members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Team<select value={team} onChange={e=>setTeam(e.target.value)}><option value="">Choose a team</option>{detail.teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><Button type="submit" disabled={busy||!person||!team}>Add to team</Button></form>}
  </>}
 </section>;
}
