import {SHARED_ACCOUNT_SLOTS, SHARED_ACCOUNT_PROVIDERS} from '../projects';
import {useEffect,useId,useRef,useState} from 'react';import {Button} from './ui';import {sharedAccountRequest} from '../remoteExecution/sharedAccountsClient';import './sharedAccounts.css';import {subscriptionCredential} from '../remoteExecution/sharedAccountCredential';
type Project={id:string;name:string};type Slot=typeof SHARED_ACCOUNT_SLOTS[number];type Binding={projectId:string;slot:Slot;accountId:string};
const names:Record<Slot,string>={git:'GitHub',claude:'Claude',codex:'Codex'};
export function SharedAccountsPanel({workspaceId,projects}:{workspaceId:string;projects:Project[]}){
 const uid=useId();
 const [bindings,setBindings]=useState<Binding[]>([]),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [authType,setAuthType]=useState<'api-key'|'oauth'>('api-key');
 const [edit,setEdit]=useState<{project:Project;slot:Slot}|null>(null),[account,setAccount]=useState(''),[key,setKey]=useState(''),[repository,setRepository]=useState(''),[remove,setRemove]=useState<string|null>(null);const epoch=useRef(0);
 useEffect(()=>{epoch.current++;setBindings([]);setEdit(null);setKey('');setAuthType('api-key');setError('');setNotice('');setRemove(null);setBusy(false);setLoading(false);return()=>{epoch.current++;};},[workspaceId]);
 async function refresh(){const current=epoch.current;setLoading(true);setError('');try{const data=await sharedAccountRequest<{bindings:Binding[]}>(workspaceId);if(current===epoch.current)setBindings(data.bindings);}catch{if(current===epoch.current)setError('Shared accounts are unavailable. Start or update this workspace, then try again.');}finally{if(current===epoch.current)setLoading(false);}}
 function configure(project:Project,slot:Slot){setEdit({project,slot});setAccount(bindings.find(b=>b.projectId===project.id&&b.slot===slot)?.accountId??`${slot}-${project.id}`.slice(0,128));setKey('');setAuthType('api-key');setRepository('');setError('');setNotice('');}
 async function save(){if(!edit)return;const current=epoch.current;setBusy(true);setError('');setNotice('');const secret=key.trim();setKey('');try{
  const provider=SHARED_ACCOUNT_PROVIDERS[edit.slot];
  const credential=edit.slot!=='git'&&authType==='oauth'?subscriptionCredential(SHARED_ACCOUNT_PROVIDERS[edit.slot],secret):{provider:edit.slot==='git'?'github':provider,token:secret,...(edit.slot==='git'?{repository:repository.trim()}:{})};
  await sharedAccountRequest(workspaceId,{action:'import',accountId:account,credential});
  if(current!==epoch.current)return;
  const result=await sharedAccountRequest<{bindings:Binding[]}>(workspaceId,{action:'bind',accountId:account,projectId:edit.project.id,slot:edit.slot});
  if(current===epoch.current){setBindings(result.bindings);setEdit(null);setNotice('Shared account saved.');}
 }catch{if(current===epoch.current)setError('The account could not be saved or selected. Check its details and try again.');}finally{if(current===epoch.current)setBusy(false);}}
 async function removeAccount(){if(!remove)return;const current=epoch.current;setBusy(true);setError('');try{await sharedAccountRequest(workspaceId,{action:'remove',accountId:remove});if(current===epoch.current){setBindings(rows=>rows.filter(b=>b.accountId!==remove));setRemove(null);setNotice('Shared account removed.');}}catch{if(current===epoch.current)setError('The account could not be removed. Try again.');}finally{if(current===epoch.current)setBusy(false);}}
 return <details className="shared-accounts" onToggle={e=>{if(e.currentTarget.open)void refresh();else{setEdit(null);setKey('');setRemove(null);}}}><summary>Shared workspace accounts</summary><div className="shared-accounts-content">
  <header><p>Select provider accounts for these projects. Members need an explicit shared-access grant to use them.</p><Button size="sm" disabled={loading||busy} onClick={()=>void refresh()}>Refresh accounts</Button></header>
  <p className="shared-accounts-note">Share a provider API key or explicitly import a Claude or Codex subscription sign-in. Members’ personal accounts remain separate.</p>
  {error&&<p role="alert" className="shared-accounts-error">{error}</p>}{notice&&<p role="status">{notice}</p>}
  {loading&&<div className="shared-accounts-loading" role="status" aria-label="Loading shared accounts"><span/><span/><span/></div>}
  {!loading&&!projects.length&&<p>Load or import projects before choosing shared accounts.</p>}
  {projects.map(project=><section className="shared-account-project" key={project.id}><h4>{project.name}</h4>{SHARED_ACCOUNT_SLOTS.map(slot=>{const binding=bindings.find(b=>b.projectId===project.id&&b.slot===slot);return <div className="shared-account-row" key={slot}><span className="shared-account-provider">{names[slot]}</span><span className={binding?'shared-account-status configured':'shared-account-status'}>{binding?binding.accountId:'Personal accounts'}</span><div className="shared-account-actions"><Button size="sm" disabled={busy||loading} onClick={()=>configure(project,slot)} aria-label={`Configure ${names[slot]} for ${project.name}`}>{binding?'Change':'Configure'}</Button>{binding&&<Button size="sm" variant="ghost" disabled={busy} onClick={()=>setRemove(binding.accountId)} aria-label={`Remove ${names[slot]} account ${binding.accountId}`}>Remove</Button>}</div></div>;})}</section>)}
  {edit&&<form className="shared-account-editor" onSubmit={e=>{e.preventDefault();void save();}}><h4>{names[edit.slot]} for {edit.project.name}</h4><label>Account name<input aria-label="Account name" required maxLength={128} pattern="[A-Za-z0-9_-]{1,128}" value={account} onChange={e=>setAccount(e.target.value)} disabled={busy}/><small>Letters, numbers, hyphens or underscores.</small></label>{edit.slot!=='git'&&<label>Account type<select aria-label="Account type" value={authType} disabled={busy} onChange={e=>{setAuthType(e.target.value as 'api-key'|'oauth');setKey('');setError('');}}><option value="api-key">API key</option><option value="oauth">Subscription sign-in</option></select></label>}{edit.slot==='git'&&<label>GitHub repository<input required placeholder="organization/repository" value={repository} onChange={e=>setRepository(e.target.value)} disabled={busy}/></label>}<label>{edit.slot==='git'?'GitHub access token':authType==='oauth'?'Subscription sign-in JSON':'Provider API key'}<input aria-label={edit.slot==='git'?'GitHub access token':authType==='oauth'?'Subscription sign-in JSON':'Provider API key'} aria-describedby={`${uid}-key-hint`} required type="password" autoComplete="new-password" spellCheck={false} maxLength={authType==='oauth'?32768:8192} value={key} onChange={e=>setKey(e.target.value)} disabled={busy}/><small id={`${uid}-key-hint`}>{authType==='oauth'?'Paste only the sign-in JSON export you choose to share. Refresh credentials stay in the private management service.':'Stored in this workspace’s private management service.'}</small></label>{bindings.filter(b=>b.accountId===account).length>1&&<p className="shared-account-reuse">Saving replaces this account’s credentials for every project using it.</p>}<footer><Button type="button" disabled={busy} onClick={()=>{setEdit(null);setKey('');}}>Cancel</Button><Button variant="accent" type="submit" disabled={busy||!key.trim()||!account||(edit.slot==='git'&&!repository.trim())}>{busy?'Saving…':'Save account'}</Button></footer></form>}
  {remove&&<div className="shared-account-confirm" role="group" aria-label="Remove shared account"><strong>Remove {remove}?</strong><p>All projects using this account lose its shared access. Personal accounts stay available.</p><Button disabled={busy} onClick={()=>setRemove(null)}>Cancel</Button><Button variant="danger" disabled={busy} onClick={()=>void removeAccount()}>Remove account</Button></div>}
 </div></details>;
}
