import {it,expect,vi,afterEach} from 'vitest';import {render,screen,fireEvent,waitFor,cleanup} from '@testing-library/react';import {SharingSetupPanel,sharingCandidates} from './SharingSetupPanel';import type {WorkspaceState} from '../projects';
const state=vi.hoisted(()=>({host:null as null|{connection:{workspaceId:string};client:{workspace:ReturnType<typeof vi.fn>};invoke:ReturnType<typeof vi.fn>},invoke:vi.fn()}));vi.mock('../remoteExecution/workspace',()=>({activeWorkspace:()=>state.host}));vi.mock('@tauri-apps/api/core',()=>({invoke:state.invoke}));afterEach(()=>{cleanup();state.host=null;state.invoke.mockReset();});
it('candidate paths preserve project grouping and reject home or traversal folders',()=>{
 const store={projects:[{id:'app',name:'App',components:[{id:'web',label:'Web',path:'/workspace/app/web'},{id:'api',label:'API',path:'/workspace/app/api'}]},{id:'private',name:'Private',components:[{id:'auth',label:'Auth',path:'/home/agent/.claude'}]},{id:'escape',name:'Escape',components:[{id:'bad',label:'Bad',path:'/workspace/../home'}]}]} as WorkspaceState;
 const result=sharingCandidates(store);expect(result[0].components).toEqual([{id:'web',label:'Web',source:'app/web',relativePath:'web'},{id:'api',label:'API',source:'app/api',relativePath:'api'}]);expect(result[1].error).toBeTruthy();expect(result[2].error).toBeTruthy();
});
it('preparing sharing requires explicit interruption and selected project folders',async()=>{
 const request=vi.fn(async(_id,_route,body)=>({status:body?'running':'not-enabled',phase:'choose-projects',error:null}));state.host={connection:{workspaceId:'ws'},client:{workspace:request},invoke:vi.fn(async()=>JSON.stringify({projects:[{id:'app',name:'App',components:[{id:'web',label:'Web',path:'/workspace/repo'}]}]}))};
 render(<SharingSetupPanel workspaceId="ws"/>);fireEvent.click(screen.getByText('Enable workspace sharing'));fireEvent.click(await screen.findByRole('button',{name:'Find workspace projects'}));fireEvent.click(await screen.findByRole('checkbox',{name:'App'}));expect(screen.getByRole('button',{name:'Prepare shared storage'})).toBeDisabled();fireEvent.click(screen.getByRole('checkbox',{name:/I am ready to stop/}));fireEvent.click(screen.getByRole('button',{name:'Prepare shared storage'}));
 await waitFor(()=>expect(request).toHaveBeenCalledWith('ws','/sharing-setup',{action:'start',confirmInterrupt:true,projects:[{id:'app',name:'App',components:[{id:'web',label:'Web',source:'repo',relativePath:'.'}]}]}));
});
it('ready storage activation is performed by authenticated account service',async()=>{
 state.host={connection:{workspaceId:'ws'},client:{workspace:vi.fn(async()=>({status:'ready',phase:'ready',error:null}))},invoke:vi.fn()};state.invoke.mockResolvedValue({activated:true});render(<SharingSetupPanel workspaceId="ws"/>);fireEvent.click(screen.getByText('Enable workspace sharing'));fireEvent.click(await screen.findByRole('button',{name:'Activate sharing'}));await waitFor(()=>expect(state.invoke).toHaveBeenCalledWith('canopy_account_request',{route:'/api/operations',body:{action:'activate-sharing',workspaceId:'ws'}}));await screen.findByRole('button',{name:'Sharing enabled'});
});
