import {useEffect,useRef,useState} from 'react';
import {activeWorkspace} from '../remoteExecution/workspace';
import {RemoteTerminal} from '../remoteExecution/RemoteTerminal';
import {sharedSessionClient} from '../remoteExecution/sharedSessionClient';
import type {RemoteExecutionClient} from '../remoteExecution/client';
import {Button} from './ui';
import './sharedSessions.css';
type Publication={id:string;projectId:string;title:string;mode:'view'|'interact';expiresAt:number;collaborative?:boolean};
type Session={id:number;title:string;exitCode:number|null};
export function SharedSessionsPanel({workspaceId,owner,projects}:{workspaceId:string;owner:boolean;projects?:{id:string;name:string}[]}){
 const [rows,setRows]=useState<Publication[]>([]),[local,setLocal]=useState<Session[]>([]),[selected,setSelected]=useState<Publication|null>(null),[open,setOpen]=useState(false),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [project,setProject]=useState(''),[session,setSession]=useState(''),[title,setTitle]=useState(''),[ack,setAck]=useState(false),[catalog,setCatalog]=useState<{id:string;name:string}[]>([]);const epoch=useRef(0);
 const [viewClient,setViewClient]=useState<RemoteExecutionClient|null>(null);
 const host=activeWorkspace(),client=host?.connection.workspaceId===workspaceId?host.client:viewClient;
 useEffect(()=>{const reset=()=>{epoch.current++;setViewClient(null);setRows([]);setLocal([]);setCatalog([]);setSelected(null);setOpen(false);setProject('');setSession('');setTitle('');setAck(false);setError('');setBusy(false);setLoading(false);};reset();window.addEventListener('canopy:account-changed',reset);return()=>{epoch.current++;window.removeEventListener('canopy:account-changed',reset);};},[workspaceId]);
 async function connectViewing(){const current=epoch.current;setBusy(true);setError('');try{const next=await sharedSessionClient(workspaceId,()=>current===epoch.current);if(current===epoch.current)setViewClient(next);}catch(e){if(current===epoch.current)setError(String(e));}finally{if(current===epoch.current)setBusy(false);}}
 const projectChoices=projects??catalog;
 async function refresh(){if(!client)return;const current=epoch.current;setLoading(true);try{const result=await client.workspace<{sessions:Publication[]}>(workspaceId,'/shared-sessions');if(current!==epoch.current)return;setRows(result.sessions);setSelected(old=>old?result.sessions.find(p=>p.id===old.id)??null:null);if(!projects){const data=await client.workspace<{projects:{id:string;name:string}[]}>(workspaceId,'/projects');if(current===epoch.current)setCatalog(data.projects);}if(owner&&client===host?.client){const sessions=await client.workspace<Session[]>(workspaceId,'/sessions');if(current===epoch.current)setLocal(sessions.filter(s=>s.exitCode==null));}if(current===epoch.current)setError('');}catch{if(current===epoch.current){setSelected(null);setRows([]);setError('Shared sessions are unavailable or your access has changed.');}}finally{if(current===epoch.current)setLoading(false);}}
 useEffect(()=>{if(!open||!client)return;void refresh();const timer=setInterval(()=>void refresh(),5000);return()=>clearInterval(timer);},[open,client,workspaceId,owner]);
 async function action(body:unknown){if(!client)return;const current=epoch.current;setBusy(true);setError('');try{const result=await client.workspace<{sessions:Publication[]}>(workspaceId,'/shared-sessions',body);if(current===epoch.current){setRows(result.sessions);setSelected(old=>old?result.sessions.find(p=>p.id===old.id)??null:null);setAck(false);}}catch(e){if(current===epoch.current)setError(String(e));}finally{if(current===epoch.current)setBusy(false);}}
 return <details className="shared-sessions-panel" open={open} onToggle={e=>setOpen(e.currentTarget.open)}><summary>Shared sessions</summary><div className="shared-sessions-content">
  {!client?<><p>View published sessions without opening a personal runtime. Opening this panel does not start the workspace.</p><Button disabled={busy} onClick={()=>void connectViewing()}>{busy?'Connecting…':'View shared sessions'}</Button>{error&&<p role="alert">{error}</p>}</>:<>
   <header><p>Let teammates watch or join a terminal in this workspace.</p><Button size="sm" variant="ghost" disabled={loading||busy} title="Refresh shared sessions" aria-label="Refresh sessions" onClick={()=>void refresh()}>↻</Button></header>
   {loading&&!rows.length&&<p role="status">Loading shared sessions…</p>}{error&&<p role="alert">{error}</p>}
   {!loading&&!rows.length&&!error&&<p className="shared-session-empty">Nothing shared yet. Your terminals stay private until you share one.</p>}
   {rows.map(p=><div className="shared-session-row" key={p.id}><Button size="sm" onClick={()=>setSelected(p)}>{p.title}</Button><span>{p.mode==='interact'?'Can interact':'View only'} · {projectChoices.find(item=>item.id===p.projectId)?.name??p.projectId}</span>{owner&&<Button size="sm" variant="danger" disabled={busy} onClick={()=>void action({action:'revoke',id:p.id})}>{p.collaborative?'Stop sharing and shell':'Stop sharing'}</Button>}</div>)}
   {selected&&<section className="shared-session-preview"><header><strong>{selected.title} · {selected.mode==='interact'?'Collaborative shell':'View only'}</strong><Button size="sm" onClick={()=>setSelected(null)}>Close terminal</Button></header><RemoteTerminal key={selected.id} client={client} workspaceId={workspaceId} sessionId={0} sharedSessionId={selected.id} writable={selected.mode==='interact'}/></section>}
   {owner&&<form onSubmit={e=>e.preventDefault()} className="shared-session-form">
    <div className="shared-session-line"><span className="shared-session-label">Share with</span><select aria-label="Project" value={project} onChange={e=>setProject(e.target.value)}><option value="">Choose a project</option>{projectChoices.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><small>Members with access to this project can see it.</small></div>
    <div className="shared-session-action"><div className="shared-session-line"><span className="shared-session-label">Pair live</span><input aria-label="Session name" value={title} maxLength={80} onChange={e=>setTitle(e.target.value)} placeholder="Session name, e.g. Pair on the frontend"/><Button size="sm" disabled={busy||!project||!title.trim()} onClick={()=>void action({action:'create',projectId:project,title})}>Start shared shell</Button></div><small>A fresh shell with only this project, not your Git or agent logins. Anyone invited can edit its files. Ends after 1 hour.</small></div>
    <div className="shared-session-action"><div className="shared-session-line"><span className="shared-session-label">Let others watch</span><select aria-label="Your terminal" value={session} onChange={e=>{setSession(e.target.value);setAck(false);}}><option value="">Choose a running terminal</option>{local.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select><label className="shared-session-disclosure"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>Nothing private on screen</label><Button size="sm" disabled={busy||!project||!session||!(title.trim()||local.find(s=>String(s.id)===session)?.title)||!ack} onClick={()=>void action({action:'publish',sessionId:Number(session),projectId:project,title:title.trim()||local.find(s=>String(s.id)===session)?.title||'Shared terminal',mode:'view',acknowledged:true})}>Share view-only</Button></div><small>View only. Viewers see everything this terminal shows, including earlier output.</small></div>
   </form>}
  </>}
 </div></details>;
}
