import {render,screen,fireEvent,waitFor,act,within} from '@testing-library/react';
import {it,expect,vi,beforeEach} from 'vitest';
import {WorkspaceSharing} from './WorkspaceSharing';
const invoke=vi.hoisted(()=>vi.fn());vi.mock('@tauri-apps/api/core',()=>({invoke}));
const owner=[{role:'owner',permissions:{projects:'all'}}];
function fixture(overrides:Record<string,unknown>={}){invoke.mockImplementation(async(_,{body}={body:{}})=>{if(body.action in overrides){const result=overrides[body.action];if(result instanceof Error)throw result;return typeof result==='function'?(result as Function)(body):result;}return body.action==='workspace-team-list'?{organizationId:'org',teams:[{id:'team',name:'Engineering'}],grants:[],yourAccess:owner}:body.action==='workspace-person-list'?{people:[{id:'ada',name:'Ada',email:'ada@example.invalid'}],grants:[]}:body.action==='workspace-organization-list'?{organizationId:'org',organizationName:'Canopy Labs',grant:null}:body.action==='workspace-project-list'?{projects:[{id:'app',name:'Product',components:[{id:'web',name:'Frontend'},{id:'api',name:'Backend'}]}]}:{ok:true};});}
beforeEach(()=>invoke.mockReset());
it('starts with a compact access roster and opens only the chosen form',async()=>{fixture();render(<WorkspaceSharing workspaceId="workspace"/>);await screen.findByText('No teams have access');expect(screen.queryByRole('combobox')).toBeNull();expect(screen.queryByText('Share workspace')).toBeNull();expect(screen.queryByText('Shared workspace accounts')).toBeNull();fireEvent.click(screen.getByRole('button',{name:'+ Add access'}));expect(screen.getByRole('combobox',{name:'Team'})).toBeVisible();expect(screen.getByRole('radio',{name:'Developer'})).toBeChecked();expect(screen.queryByRole('combobox',{name:'Project scope'})).toBeNull();expect(screen.getByText(/The whole workspace/)).toBeVisible();expect(screen.queryByRole('combobox',{name:'Person'})).toBeNull();});
it('editing an older project-scoped grant saves whole-workspace access and keeps explicit resources',async()=>{const permissions={projects:'selected',projectIds:['app'],git:'shared',agents:'personal',sessions:'view'};fixture({'workspace-team-list':{organizationId:'org',teams:[{id:'team',name:'Engineering'}],grants:[{team_id:'team',name:'Engineering',role:'member',permissions}],yourAccess:owner}});render(<WorkspaceSharing workspaceId="workspace"/>);fireEvent.click(await screen.findByRole('button',{name:'Edit'}));fireEvent.click(screen.getByRole('radio',{name:'Viewer'}));fireEvent.click(screen.getByRole('button',{name:'Save changes'}));await waitFor(()=>expect(invoke).toHaveBeenCalledWith('canopy_account_request',{route:'/api/teams',body:{action:'workspace-team-grant',workspaceId:'workspace',teamId:'team',role:'viewer',permissions:{...permissions,projects:'all',projectIds:[]}}}));});
it('grants a person with personal credentials by default',async()=>{fixture();render(<WorkspaceSharing workspaceId="workspace"/>);await screen.findByText('No teams have access');fireEvent.click(screen.getByRole('tab',{name:/People/}));fireEvent.click(screen.getByRole('button',{name:'Add a person'}));fireEvent.change(screen.getByRole('combobox',{name:'Person'}),{target:{value:'ada'}});fireEvent.click(screen.getByRole('radio',{name:'Developer'}));fireEvent.click(screen.getByRole('button',{name:'Grant access'}));await waitFor(()=>expect(invoke).toHaveBeenCalledWith('canopy_account_request',{route:'/api/teams',body:{action:'workspace-person-grant',workspaceId:'workspace',userId:'ada',role:'member',permissions:{projects:'all',projectIds:[],git:'personal',agents:'personal',sessions:'private'}}}));});
it('Everyone grants current and future organization members without copying people',async()=>{fixture();render(<WorkspaceSharing workspaceId="workspace"/>);await screen.findByText('No teams have access');fireEvent.click(screen.getByRole('tab',{name:/Everyone/}));fireEvent.click(screen.getByRole('button',{name:'Give everyone access'}));expect(screen.getByRole('combobox',{name:'Organization'})).toHaveValue('org');fireEvent.click(screen.getByRole('button',{name:'Grant access'}));await waitFor(()=>expect(invoke).toHaveBeenCalledWith('canopy_account_request',{route:'/api/teams',body:{action:'workspace-organization-grant',workspaceId:'workspace',organizationId:'org',role:'viewer',permissions:{projects:'all',projectIds:[],git:'personal',agents:'personal',sessions:'private'}}}));});
it('removes organization access only after explicit confirmation',async()=>{fixture({'workspace-organization-list':{organizationId:'org',organizationName:'Canopy Labs',grant:{organization_id:'org',name:'Canopy Labs',role:'viewer',permissions:{projects:'all'}}}});render(<WorkspaceSharing workspaceId="workspace"/>);await screen.findByText('No teams have access');fireEvent.click(screen.getByRole('tab',{name:/Everyone/}));fireEvent.click(screen.getByRole('button',{name:'Remove'}));expect(invoke.mock.calls.some(([,args])=>args.body.action.endsWith('-revoke'))).toBe(false);fireEvent.click(screen.getByRole('button',{name:'Confirm removal'}));await waitFor(()=>expect(invoke).toHaveBeenCalledWith('canopy_account_request',{route:'/api/teams',body:{action:'workspace-organization-revoke',workspaceId:'workspace',organizationId:'org'}}));});
it('owners grant the whole workspace even when project metadata is unavailable',async()=>{const permissions={projects:'selected',projectIds:['app'],git:'personal',agents:'personal',sessions:'private'};fixture({'workspace-project-list':Error('Workspace offline'),'workspace-person-list':{people:[{id:'ada',name:'Ada',email:'ada@example.invalid'}],grants:[{user_id:'ada',name:'Ada',email:'ada@example.invalid',role:'member',permissions}]}});render(<WorkspaceSharing workspaceId="workspace"/>);await screen.findByText('No teams have access');fireEvent.click(screen.getByRole('tab',{name:/People/}));fireEvent.click(screen.getByRole('button',{name:'Edit'}));expect(screen.queryByRole('checkbox',{name:'app'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Save changes'}));await waitFor(()=>expect(invoke).toHaveBeenCalledWith('canopy_account_request',{route:'/api/teams',body:{action:'workspace-person-grant',workspaceId:'workspace',userId:'ada',role:'member',permissions:{...permissions,projects:'all',projectIds:[]}}}));});
it('normalizes legacy grants and blocks scoped administrators from editing higher grants',async()=>{fixture({'workspace-team-list':{organizationId:'org',teams:[{id:'team',name:'Engineering'}],grants:[{team_id:'team',name:'Engineering',role:'admin',permissions:{projects:'all'}}],yourAccess:[{role:'admin',permissions:{projects:'selected',projectIds:['app']}}]}});render(<WorkspaceSharing workspaceId="workspace"/>);expect(await screen.findByRole('button',{name:'Edit'})).toBeDisabled();expect(screen.getByRole('button',{name:'Remove'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'+ Add access'}));expect(screen.queryByRole('radio',{name:'Admin'})).toBeNull();expect(within(screen.getByRole('combobox',{name:'Project scope'})).queryByRole('option',{name:'All projects'})).toBeNull();fireEvent.change(screen.getByRole('combobox',{name:'Team'}),{target:{value:'team'}});expect(screen.getByRole('button',{name:'Save changes'})).toBeDisabled();});
it('resource choices are collapsed by default and remain bounded by delegated resources',async()=>{fixture({'workspace-team-list':{organizationId:'org',teams:[{id:'team',name:'Engineering'}],grants:[],yourAccess:[{role:'admin',permissions:{projects:'all'}},{role:'admin',permissions:{projects:'selected',projectIds:['app'],git:'shared'}}]}});render(<WorkspaceSharing workspaceId="workspace"/>);await screen.findByText('No teams have access');fireEvent.click(screen.getByRole('button',{name:'+ Add access'}));const details=screen.getByText('Shared resources').closest('details');expect(details).not.toHaveAttribute('open');fireEvent.click(screen.getByText('Shared resources'));expect(within(screen.getByRole('combobox',{name:'Git access'})).getByRole('option',{name:'Use shared workspace accounts'})).toBeDisabled();});
it('ignores responses and pending grants from an old account or workspace',async()=>{let resolveOld!:(value:unknown)=>void;fixture({'workspace-team-list':(body:{workspaceId:string})=>body.workspaceId==='old'?new Promise(resolve=>{resolveOld=resolve;}):{organizationId:'org',teams:[],grants:[],yourAccess:owner}});const view=render(<WorkspaceSharing workspaceId="old"/>);view.rerender(<WorkspaceSharing workspaceId="new"/>);await screen.findByText('No teams have access');await act(async()=>resolveOld({organizationId:'org',teams:[],grants:[{team_id:'stale',name:'Old private team',role:'member'}],yourAccess:owner}));expect(screen.queryByText('Old private team')).toBeNull();fireEvent.click(screen.getByRole('button',{name:'+ Add access'}));await act(async()=>window.dispatchEvent(new Event('canopy:account-changed')));await screen.findByText('No teams have access');expect(screen.queryByRole('combobox',{name:'Team'})).toBeNull();});
it('retries a metadata failure without waking the workspace',async()=>{let fail=true;fixture({'workspace-team-list':()=>{if(fail)throw Error('Access unavailable');return {organizationId:'org',teams:[],grants:[],yourAccess:owner};}});render(<WorkspaceSharing workspaceId="workspace"/>);await screen.findByRole('alert');fail=false;fireEvent.click(screen.getByRole('button',{name:'Retry'}));await screen.findByText('No teams have access');expect(invoke.mock.calls.every(([,args])=>!['resume','advance','start'].includes(args.body.action))).toBe(true);});
it('a team grant defaults to Developer for the whole workspace',async()=>{fixture();render(<WorkspaceSharing workspaceId="workspace"/>);await screen.findByText('No teams have access');fireEvent.click(screen.getByRole('button',{name:'+ Add access'}));fireEvent.change(screen.getByRole('combobox',{name:'Team'}),{target:{value:'team'}});fireEvent.click(screen.getByRole('button',{name:'Grant access'}));await waitFor(()=>expect(invoke).toHaveBeenCalledWith('canopy_account_request',{route:'/api/teams',body:{action:'workspace-team-grant',workspaceId:'workspace',teamId:'team',role:'member',permissions:{projects:'all',projectIds:[],git:'personal',agents:'personal',sessions:'private'}}}));});
it('does not report a previous account mutation as a new account success',async()=>{let finish!:(value:unknown)=>void;fixture({'workspace-team-grant':()=>new Promise(resolve=>{finish=resolve;})});render(<WorkspaceSharing workspaceId="workspace"/>);await screen.findByText('No teams have access');fireEvent.click(screen.getByRole('button',{name:'+ Add access'}));fireEvent.change(screen.getByRole('combobox',{name:'Team'}),{target:{value:'team'}});fireEvent.click(screen.getByRole('button',{name:'Grant access'}));await waitFor(()=>expect(finish).toBeTypeOf('function'));await act(async()=>window.dispatchEvent(new Event('canopy:account-changed')));await screen.findByText('No teams have access');const before=invoke.mock.calls.filter(([,args])=>args?.body?.action==='workspace-team-list').length;await act(async()=>finish({ok:true}));expect(screen.queryByText('Access granted.')).toBeNull();expect(invoke.mock.calls.filter(([,args])=>args?.body?.action==='workspace-team-list')).toHaveLength(before);});
it('explains role capabilities where the user chooses a role and keeps an edited recipient fixed',async()=>{fixture({'workspace-person-list':{people:[{id:'ada',name:'Ada',email:'ada@example.invalid'}],grants:[{user_id:'ada',name:'Ada',email:'ada@example.invalid',role:'member',permissions:{projects:'all'}}]}});render(<WorkspaceSharing workspaceId="workspace"/>);await screen.findByText('No teams have access');fireEvent.click(screen.getByRole('tab',{name:/People/}));fireEvent.click(screen.getByRole('button',{name:'Edit'}));expect(screen.queryByRole('combobox',{name:'Person'})).toBeNull();expect(screen.getByText('Ada')).toBeVisible();expect(screen.getByRole('radio',{name:'Developer'})).toBeChecked();expect(screen.getByText('Browse permitted files and view explicitly shared sessions.')).toBeVisible();expect(screen.getByText('Edit files, run tools and resume the workspace.')).toBeVisible();expect(screen.getByText('Developer access plus permission management within assigned scope.')).toBeVisible();fireEvent.click(screen.getByRole('radio',{name:'Admin'}));expect(screen.getByRole('radio',{name:'Admin'})).toBeChecked();fireEvent.click(screen.getByRole('button',{name:'Save changes'}));await waitFor(()=>expect(invoke).toHaveBeenCalledWith('canopy_account_request',{route:'/api/teams',body:{action:'workspace-person-grant',workspaceId:'workspace',userId:'ada',role:'admin',permissions:{projects:'all',projectIds:[],git:'personal',agents:'personal',sessions:'private'}}}));});
it('shows one sharing line: not shared until a grant, then getting ready, then on',async()=>{
 let sharing={state:'off',enabled:false,ready:false,error:null};
 fixture({'sharing-status':()=>({sharing})});render(<WorkspaceSharing workspaceId="workspace"/>);
 expect(await screen.findByText('Not shared · Add a person or team to share this workspace')).toBeInTheDocument();
 sharing={state:'pending',enabled:true,ready:false,error:null};
 fireEvent.click(screen.getByRole('button',{name:'+ Add access'}));fireEvent.change(screen.getByRole('combobox',{name:'Team'}),{target:{value:'team'}});fireEvent.click(screen.getByRole('button',{name:'Grant access'}));
 expect(await screen.findByText('Getting ready · Members can connect in a minute')).toBeInTheDocument();
 expect(invoke.mock.calls.some(([,args])=>['sharing-on','sharing-start','activate-sharing'].includes(args.body.action))).toBe(false);
});
it('a failed readiness check shows its reason with Retry',async()=>{
 let sharing:{state:string;enabled:boolean;ready:boolean;error:string|null}={state:'failed',enabled:true,ready:false,error:'The workspace host needs an update to share. Restart the workspace to update it'};
 fixture({'sharing-status':()=>({sharing}),'sharing-retry':()=>{sharing={state:'ready',enabled:true,ready:true,error:null};return {sharing};}});
 render(<WorkspaceSharing workspaceId="workspace"/>);
 expect(await screen.findByText('Not ready: The workspace host needs an update to share. Restart the workspace to update it')).toBeInTheDocument();
 fireEvent.click(screen.getByRole('button',{name:'Retry'}));
 expect(await screen.findByText('Sharing on · People with access can connect')).toBeInTheDocument();
});
it('turning sharing off asks first',async()=>{
 fixture({'sharing-status':{sharing:{state:'ready',enabled:true,ready:true,error:null}},'sharing-off':{sharing:{state:'off',enabled:false,ready:false,error:null}},'workspace-team-list':{organizationId:'org',teams:[{id:'team',name:'Core'}],grants:[{team_id:'team',name:'Core',role:'member',permissions:{projects:'all'}}],yourAccess:owner}});
 render(<WorkspaceSharing workspaceId="workspace"/>);
 fireEvent.click(await screen.findByRole('button',{name:'Turn off'}));expect(invoke.mock.calls.some(([,args])=>args.body.action==='sharing-off')).toBe(false);
 fireEvent.click(screen.getByRole('button',{name:'Turn off sharing'}));
 expect(await screen.findByText('Sharing off · People with access can’t connect')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Turn on sharing'})).toBeEnabled();
});
it('shows no sharing controls to a scoped administrator',async()=>{
 fixture({'workspace-team-list':{organizationId:'org',teams:[],grants:[],yourAccess:[{role:'admin',permissions:{projects:'all'}}]}});
 render(<WorkspaceSharing workspaceId="workspace"/>);await screen.findByText('No teams have access');
 expect(screen.queryByRole('status',{name:'Sharing'})).toBeNull();expect(invoke.mock.calls.some(([,args])=>args.body.action==='sharing-status')).toBe(false);
});
