import {useEffect,useId,useRef,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {canDelegateWorkspacePolicy} from '../../packages/control-plane/lib/delegation.mjs';
// @ts-expect-error Shared policy module has no TypeScript declaration.
import {sharingPolicy,canRevoke} from '../../packages/control-plane/lib/team-policy.mjs';
import {Button} from './ui';
import './workspaceSharing.css';
type ShareProject={id:string;name:string;components:{id:string;name:string}[]};
type Policy={projects:string;projectIds:string[];git:string;agents:string;sessions:string};
type Access={role:string;permissions?:Partial<Policy>};
type TeamGrant=Access&{team_id:string;name:string};
type PersonGrant=Access&{user_id:string;name:string;email:string};
type OrgGrant=Access&{organization_id:string;name:string};
type Detail={organizationId:string|null;teams:{id:string;name:string}[];grants:TeamGrant[];yourAccess?:Access[]};
type People={people:{id:string;name:string;email:string}[];grants:PersonGrant[]};
type OrganizationAccess={organizationId:string|null;organizationName:string|null;grant:OrgGrant|null};
type Tab='team'|'person'|'organization';
type Entry={id:string;name:string;subtitle?:string;email?:string;role:string;permissions?:Partial<Policy>};
type Editor={id:string;role:string;permissions:Policy;existing:Entry|null};
const request=<T,>(body:unknown)=>invoke<T>('canopy_account_request',{route:'/api/teams',body});
const normalize=(permissions?:Partial<Policy>):Policy=>sharingPolicy(permissions??{});
const roleName=(role:string)=>role==='member'?'Developer':role==='admin'?'Admin':'Viewer';
const noun:Record<Tab,string>={team:'team',person:'person',organization:'organization'};
export function WorkspaceSharing({workspaceId,workspaceName}:{workspaceId:string;workspaceName?:string}){
 const [detail,setDetail]=useState<Detail|null>(null),[people,setPeople]=useState<People>({people:[],grants:[]});
 const [orgAccess,setOrgAccess]=useState<OrganizationAccess|null>(null),[organizations,setOrganizations]=useState<{id:string;name:string}[]>([]),[organization,setOrganization]=useState('');
 const [tab,setTab]=useState<Tab>('team'),[editor,setEditor]=useState<Editor|null>(null),[remove,setRemove]=useState<Entry|null>(null);
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [projects,setProjects]=useState<ShareProject[]>([]),[projectError,setProjectError]=useState(''),[projectsLoading,setProjectsLoading]=useState(false);
 const epoch=useRef(0),refreshVersion=useRef(0),formId=useId();
 const grants=detail?.yourAccess??[];
 const isOwner=grants.some(g=>g.role==='owner');
 const admins=grants.filter(g=>g.role==='admin');
 const fullDelegation=isOwner||admins.some(g=>normalize(g.permissions).projects==='all');
 const canManage=isOwner||admins.length>0;
 const defaultPolicy:Policy={projects:fullDelegation?'all':'selected',projectIds:fullDelegation?[]:[...new Set(admins.flatMap(g=>normalize(g.permissions).projectIds))].sort(),git:'personal',agents:'personal',sessions:'private'};
 const canDelegate=(policy:Partial<Policy>)=>{try{return canDelegateWorkspacePolicy(grants,policy);}catch{return false;}};
 const canChange=(entry:Entry)=>canManage&&canRevoke(isOwner?'owner':'admin',entry.role)&&canDelegate(normalize(entry.permissions));
 const entries:Entry[]=tab==='team'?(detail?.grants??[]).map(g=>({id:g.team_id,...g})):tab==='person'?people.grants.map(g=>({id:g.user_id,...g})):orgAccess?.grant?[{id:orgAccess.grant.organization_id,...orgAccess.grant,subtitle:'All current and future organization members'}]:[];
 const targets=tab==='team'?(detail?.teams??[]):tab==='person'?people.people:orgAccess?.organizationId?[{id:orgAccess.organizationId,name:orgAccess.organizationName??'Your organization'}]:[];
 const policySummary=(raw?:Partial<Policy>)=>{const p=normalize(raw);const names=p.projectIds.map(id=>projects.find(project=>project.id===id)?.name??id);return [p.projects==='all'?'All projects':names.length?names.join(', '):'No project access',p.git==='shared'?'Shared Git':null,p.agents==='shared'?'Shared agents':null,p.sessions==='view'?'View published sessions':p.sessions==='interact'?'Interact with published sessions':null].filter(Boolean).join(' · ');};
 async function refreshProjects(){const current=epoch.current;setProjectsLoading(true);setProjectError('');try{const data=await request<{projects:ShareProject[]}>({action:'workspace-project-list',workspaceId});if(current===epoch.current)setProjects(Array.isArray(data.projects)?data.projects:[]);}catch(e){if(current===epoch.current)setProjectError(String(e));}finally{if(current===epoch.current)setProjectsLoading(false);}}
 async function refresh(){const current=epoch.current,version=++refreshVersion.current;setLoading(true);try{const data=await request<Detail>({action:'workspace-team-list',workspaceId});if(current!==epoch.current||version!==refreshVersion.current)return;const [persons,orgs]=data.organizationId?await Promise.all([request<People>({action:'workspace-person-list',workspaceId}),request<OrganizationAccess>({action:'workspace-organization-list',workspaceId})]):[{people:[],grants:[]},null];if(current!==epoch.current||version!==refreshVersion.current)return;setDetail(data);setPeople(persons);setOrgAccess(orgs);if(!data.organizationId){const list=await request<{organizations:{id:string;name:string}[]}>({action:'organization-list'});if(current!==epoch.current||version!==refreshVersion.current)return;setOrganizations(list.organizations);}else void refreshProjects();}catch(e){if(current===epoch.current&&version===refreshVersion.current)setError(String(e));}finally{if(current===epoch.current&&version===refreshVersion.current)setLoading(false);}}
 useEffect(()=>{const reload=()=>{epoch.current++;refreshVersion.current++;setDetail(null);setPeople({people:[],grants:[]});setOrgAccess(null);setOrganizations([]);setOrganization('');setTab('team');setEditor(null);setRemove(null);setProjects([]);setProjectError('');setError('');setNotice('');setBusy(false);void refresh();};reload();window.addEventListener('canopy:account-changed',reload);return()=>{epoch.current++;refreshVersion.current++;window.removeEventListener('canopy:account-changed',reload);};},[workspaceId]);
 async function action(body:Record<string,unknown>,message:string){const current=epoch.current;setBusy(true);setError('');setNotice('');try{await request({...body,workspaceId});if(current!==epoch.current)return;setEditor(null);setRemove(null);setNotice(message);await refresh();}catch(e){if(current===epoch.current)setError(String(e));}finally{if(current===epoch.current)setBusy(false);}}
 function switchTab(next:Tab){setTab(next);setEditor(null);setRemove(null);setError('');setNotice('');}
 function edit(entry?:Entry){setRemove(null);setError('');setNotice('');setEditor({id:entry?.id??(tab==='organization'?orgAccess?.organizationId??'':''),role:entry?.role??'viewer',permissions:entry?normalize(entry.permissions):defaultPolicy,existing:entry??null});}
 function selectTarget(id:string){const entry=entries.find(item=>item.id===id)??null;setEditor({id,role:entry?.role??'viewer',permissions:entry?normalize(entry.permissions):defaultPolicy,existing:entry});}
 const blockedExisting=editor?.existing&&!canChange(editor.existing);
 return <section className="workspace-sharing-access" aria-label="Workspace access">
  <header className="workspace-sharing-access-heading"><div><h2>Workspace access</h2><p>{workspaceName?`Choose who can work in ${workspaceName}.`:'Choose who can work in this workspace.'}</p></div><span className="workspace-sharing-access-private-note">Personal accounts stay private</span></header>
  {error&&<div className="workspace-sharing-access-error" role="alert"><span>{error}</span><Button size="sm" disabled={busy||loading} onClick={()=>{setError('');void refresh();}}>Retry</Button></div>}
  {notice&&<p className="workspace-sharing-access-notice" role="status">{notice}</p>}
  {loading&&!detail&&<div className="workspace-sharing-access-loading" role="status">Loading workspace access…<div/><div/></div>}
  {detail&&!detail.organizationId&&<div className="workspace-sharing-access-empty"><span className="workspace-sharing-access-avatar" aria-hidden="true">+</span><h3>Share with your organization</h3><p>Choose an organization to bring its teams and people into this workspace.</p><div className="workspace-sharing-access-attach"><label>Organization<select value={organization} onChange={e=>setOrganization(e.target.value)}><option value="">Choose an organization</option>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><Button disabled={busy||loading||!organization} onClick={()=>void action({action:'organization-workspace-attach',organizationId:organization},'Workspace added to organization.')}>Add to organization</Button></div></div>}
  {detail?.organizationId&&<>
   <div className="workspace-sharing-access-toolbar"><div role="tablist" aria-label="Access recipients">{(['team','person','organization'] as const).map(value=><button key={value} type="button" role="tab" aria-selected={tab===value} onClick={()=>switchTab(value)} disabled={busy}>{value==='team'?'Teams':value==='person'?'People':'Everyone'}<span>{value==='team'?detail.grants.length:value==='person'?people.grants.length:orgAccess?.grant?1:0}</span></button>)}</div>{!editor&&<Button size="sm" disabled={!canManage||busy||loading||tab==='organization'&&!!orgAccess?.grant} onClick={()=>edit()}>+ Add access</Button>}</div>
   {!fullDelegation&&canManage&&<p className="workspace-sharing-access-scope-note">You can manage access within the projects and resources assigned to you.</p>}
   {!editor&&<>
    {entries.length>0?<div className="workspace-sharing-access-roster">{entries.map(entry=><div className="workspace-sharing-access-row" key={entry.id}><span className={`workspace-sharing-access-avatar workspace-sharing-access-avatar-${tab}`} aria-hidden="true">{tab==='organization'?'◎':entry.name.charAt(0).toUpperCase()}</span><div className="workspace-sharing-access-identity"><strong>{entry.name}</strong>{(entry.subtitle||'email' in entry)&&<small>{entry.subtitle||String(entry.email)}</small>}<p>{policySummary(entry.permissions)}</p></div><span className={`workspace-sharing-access-role workspace-sharing-access-role-${entry.role}`}>{roleName(entry.role)}</span><div className="workspace-sharing-access-row-actions"><Button size="sm" disabled={busy||!canChange(entry)} onClick={()=>edit(entry)}>Edit</Button><Button size="sm" disabled={busy||!canChange(entry)} onClick={()=>setRemove(entry)}>Remove</Button></div>{remove?.id===entry.id&&<div className="workspace-sharing-access-confirm"><div><strong>Remove access for {entry.name}?</strong><p>Access granted through other teams or directly stays in place.</p></div><Button variant="danger" size="sm" disabled={busy} onClick={()=>void action({action:`workspace-${noun[tab]}-revoke`,[tab==='team'?'teamId':tab==='person'?'userId':'organizationId']:entry.id},'Access removed.')}>Confirm removal</Button><Button size="sm" disabled={busy} onClick={()=>setRemove(null)}>Cancel</Button></div>}</div>)}</div>:<div className="workspace-sharing-access-empty"><span className={`workspace-sharing-access-avatar workspace-sharing-access-avatar-${tab}`} aria-hidden="true">{tab==='organization'?'◎':'+'}</span><h3>{tab==='team'?'No teams have access':tab==='person'?'No direct access yet':'Everyone starts without access'}</h3><p>{tab==='team'?'Give a team access once. Its members inherit the same permissions.':tab==='person'?'Add an organization member without changing their team membership.':`Grant one policy to everyone in ${orgAccess?.organizationName??'your organization'}, including future members.`}</p><Button size="sm" disabled={!canManage||busy||loading||!targets.length} onClick={()=>edit()}>{tab==='team'?'Add a team':tab==='person'?'Add a person':'Give everyone access'}</Button>{!targets.length&&tab!=='organization'&&<small>Create {tab==='team'?'a team':'an organization member'} in Teams first.</small>}</div>}
    <p className="workspace-sharing-access-footnote">Develop and Admin members can resume the workspace. Running time is billed to its owner.</p>
   </>}
   {editor&&<form className="workspace-sharing-access-editor" onSubmit={event=>{event.preventDefault();if(!editor.id||blockedExisting||!canDelegate(editor.permissions)||!isOwner&&editor.role==='admin')return;void action({action:`workspace-${noun[tab]}-grant`,[tab==='team'?'teamId':tab==='person'?'userId':'organizationId']:editor.id,role:editor.role,permissions:editor.permissions},editor.existing?'Access updated.':'Access granted.');}}>
    <header><h3>{editor.existing?'Edit access':tab==='organization'?'Give everyone access':'Add access'}</h3><p>{tab==='organization'?'Applies to all current and future organization members.':'Choose a recipient and the work they can access.'}</p></header>
    {editor.existing?<div className="workspace-sharing-access-fixed-recipient"><span className={`workspace-sharing-access-avatar workspace-sharing-access-avatar-${tab}`} aria-hidden="true">{tab==='organization'?'◎':editor.existing.name.charAt(0).toUpperCase()}</span><div><strong>{editor.existing.name}</strong><small>{editor.existing.email??(tab==='organization'?'All current and future members':'Team access')}</small></div></div>:<label className="workspace-sharing-access-recipient" htmlFor={`${formId}-recipient`}>{tab==='team'?'Team':tab==='person'?'Person':'Organization'}<select id={`${formId}-recipient`} aria-label={tab==='team'?'Team':tab==='person'?'Person':'Organization'} value={editor.id} disabled={busy||tab==='organization'} onChange={e=>selectTarget(e.target.value)}><option value="">Choose a {noun[tab]}</option>{targets.map(target=><option key={target.id} value={target.id}>{target.name?.trim()?`${target.name}${'email' in target&&target.email?` · ${target.email}`:''}`:'email' in target?String(target.email):'Unnamed team'}</option>)}</select></label>}
    <fieldset className="workspace-sharing-access-role-choices" disabled={busy}><legend>Role</legend><div>{[{value:'viewer',name:'Viewer',description:'Browse permitted files and view explicitly shared sessions.'},{value:'member',name:'Developer',description:'Edit files, run tools and resume the workspace.'},...(isOwner||editor.role==='admin'?[{value:'admin',name:'Admin',description:'Developer access plus permission management within assigned scope.'}]:[])].map(choice=><label key={choice.value} className={editor.role===choice.value?'selected':''}><input type="radio" name={`${formId}-role`} aria-label={choice.name} value={choice.value} checked={editor.role===choice.value} disabled={choice.value==='admin'&&!isOwner} onChange={()=>setEditor({...editor,role:choice.value})}/><strong>{choice.name}</strong><small>{choice.description}</small></label>)}</div></fieldset>
    <ProjectAccessEditor value={editor.permissions} onChange={permissions=>setEditor({...editor,permissions})} projects={projects} allowAll={fullDelegation} busy={busy} loading={projectsLoading} error={projectError} onReload={()=>void refreshProjects()} canShare={canDelegate}/>
    {blockedExisting&&<p className="workspace-sharing-access-error" role="alert">This existing grant exceeds your administrative access. Ask the workspace owner to change it.</p>}
    <footer><Button type="button" disabled={busy} onClick={()=>setEditor(null)}>Cancel</Button><Button variant="accent" type="submit" disabled={busy||!editor.id||!!blockedExisting||!canDelegate(editor.permissions)||!isOwner&&editor.role==='admin'}>{busy?'Saving…':editor.existing?'Save changes':'Grant access'}</Button></footer>
   </form>}
  </>}
 </section>;
}
function ProjectAccessEditor({value,onChange,projects,allowAll,busy,loading,error,onReload,canShare}:{value:Policy;onChange:(value:Policy)=>void;projects:ShareProject[];allowAll:boolean;busy:boolean;loading:boolean;error:string;onReload:()=>void;canShare:(policy:Policy)=>boolean}){
 const uid=useId(),selected=new Set(value.projectIds),available=new Set(projects.map(p=>p.id)),missing=[...selected].filter(id=>!available.has(id));
 const toggle=(id:string,checked:boolean)=>{const next=new Set(selected);if(checked)next.add(id);else next.delete(id);onChange({...value,projectIds:[...next].sort()});};
 return <fieldset className="workspace-sharing-access-policy" disabled={busy}><legend>Projects</legend><label className="workspace-sharing-access-project-mode"><span className="sr-only">Project scope</span><select aria-label="Project scope" value={value.projects} onChange={e=>onChange({...value,projects:e.target.value})}><option value="selected">Selected projects</option>{(allowAll||value.projects==='all')&&<option value="all" disabled={!allowAll}>All projects</option>}</select></label>
 {value.projects==='all'?<p className="workspace-sharing-access-help">Includes current and future projects in this workspace.</p>:<div className="workspace-sharing-access-project-list">{loading&&<p role="status">Loading projects…</p>}{error&&<div className="workspace-sharing-access-catalog-error"><p>Project details are unavailable. Saved selections are preserved.</p><small>{error}</small><Button type="button" size="sm" onClick={onReload}>Reload projects</Button></div>}{projects.map(project=><label className="workspace-sharing-access-project" key={project.id}><input type="checkbox" aria-label={project.name} aria-describedby={`${uid}-${project.id}`} checked={selected.has(project.id)} onChange={e=>toggle(project.id,e.target.checked)}/><span><strong>{project.name}</strong><small id={`${uid}-${project.id}`}>{project.components.map(c=>c.name).join(' · ')}</small></span></label>)}{missing.map(id=><label className="workspace-sharing-access-project" key={id}><input type="checkbox" aria-label={id} checked onChange={e=>toggle(id,e.target.checked)}/><span><strong>{id}</strong><small>Saved selection · details unavailable</small></span></label>)}{!loading&&!error&&!projects.length&&!missing.length&&<p>No projects are available to share.</p>}{!selected.size&&<p className="workspace-sharing-access-help">No project access will be granted.</p>}</div>}
 <details className="workspace-sharing-access-resources"><summary><span>Shared resources</span><small>{value.git==='personal'&&value.agents==='personal'&&value.sessions==='private'?'Members bring their own accounts':'Custom sharing policy'}</small></summary><div className="workspace-sharing-access-resource-fields">{(['git','agents'] as const).map(resource=><label key={resource}>{resource==='git'?'Git accounts':'Agent accounts'}<select aria-label={resource==='git'?'Git access':'Agent access'} value={value[resource]} onChange={e=>onChange({...value,[resource]:e.target.value})}><option value="personal">Use personal accounts</option><option value="shared" disabled={!canShare({...value,[resource]:'shared'})}>Use shared workspace accounts</option></select></label>)}<label>Published sessions<select aria-label="Session access" value={value.sessions} onChange={e=>onChange({...value,sessions:e.target.value})}><option value="private">Keep sessions private</option><option value="view" disabled={!canShare({...value,sessions:'view'})}>View published sessions</option><option value="interact" disabled={!canShare({...value,sessions:'interact'})}>Interact with published sessions</option></select></label></div><p className="workspace-sharing-access-help">Only explicitly published sessions are shared. Typing also requires Develop access. Removing access disconnects shared terminals.</p></details>
 </fieldset>;
}
