import test from 'node:test';import assert from 'node:assert/strict';import{selectHostSnapshot,hostSnapshotTags,verifyHostSnapshot}from'./host-snapshot.mjs';
const record={region:'ap-southeast-1',architecture:'amd64',nodeVersion:'22.20.0',dockerVersion:'28.2.2-0ubuntu1',caddyVersion:'2.6.2-5',snapshotName:'canopy-host-test',snapshotArn:'arn:aws:lightsail:ap-southeast-1:123456789012:InstanceSnapshot/1234-abcd',revision:'a'.repeat(40),runtimeSha256:'b'.repeat(64),lockSha256:'c'.repeat(64),sourceBundle:'medium_3_0',targetBundles:['medium_3_0','large_3_0','xlarge_3_0','2xlarge_3_0'],verifiedAt:'2026-10-06T00:00:00Z',proof:{docker:true,http:true,sanitized:true,bootFenced:true}};
const snapshot=()=>({name:record.snapshotName,arn:record.snapshotArn,state:'available',location:{regionName:record.region},fromBlueprintId:'ubuntu_24_04',fromBundleId:record.sourceBundle,fromAttachedDisks:[],tags:hostSnapshotTags(record)});
test('unconfigured regions keep explicit cold fallback; verified catalog selects the exact package',()=>{assert.equal(selectHostSnapshot(null,record.region,'medium_3_0'),null);assert.equal(selectHostSnapshot({version:1,entries:[record]},'us-east-1','large_3_0'),null);assert.deepEqual(selectHostSnapshot(JSON.stringify({version:1,entries:[record]}),record.region,'2xlarge_3_0'),record);assert.equal(verifyHostSnapshot(record,snapshot()),record);});
test('configured mismatches fail closed before any launch',()=>{for(const patch of [{architecture:'arm64'},{sourceBundle:'large_3_0'},{targetBundles:['unverified']},{runtimeSha256:'bad'},{proof:{docker:true,http:false,sanitized:true,bootFenced:true}},{snapshotArn:record.snapshotArn.replace('ap-southeast-1','us-east-1')}])assert.throws(()=>selectHostSnapshot({version:1,entries:[{...record,...patch}]},record.region,'medium_3_0'));assert.throws(()=>selectHostSnapshot({version:1,entries:[record,record]},record.region,'medium_3_0'));});
test('provider metadata must match identity, source, region, readiness and no attached user disk',()=>{for(const mutate of [s=>s.state='pending',s=>s.arn='foreign',s=>s.location.regionName='us-east-1',s=>s.fromBundleId='2xlarge_3_0',s=>s.fromBlueprintId='unknown',s=>s.fromAttachedDisks=[{isSystemDisk:false}],s=>s.tags=[],s=>s.tags.push(s.tags[0])]){const s=snapshot();mutate(s);assert.throws(()=>verifyHostSnapshot(record,s));}});
test('factory selection must match the active runtime checksum before provider lookup',()=>{assert.throws(()=>selectHostSnapshot({version:1,entries:[record]},record.region,'medium_3_0','d'.repeat(64)));assert.equal(selectHostSnapshot({version:1,entries:[record]},record.region,'medium_3_0',record.runtimeSha256),record);});
test('Ubuntu tilde versions produce legal tags while exact catalog versions and verification are preserved',()=>{
 const pinned={...record,dockerVersion:'29.1.3-0ubuntu3~24.04.2',caddyVersion:'2.6.2~security'};
 const tags=hostSnapshotTags(pinned),docker=tags.find(t=>t.key==='canopy-docker-version');
 assert.ok(tags.every(t=>/^[A-Za-z0-9+_.:/@= -]+$/.test(t.value)));assert.equal(Buffer.from(docker.value.slice(7),'base64url').toString(),pinned.dockerVersion);
 assert.equal(hostSnapshotTags(record).find(t=>t.key==='canopy-docker-version').value,record.dockerVersion);
 assert.equal(selectHostSnapshot({version:1,entries:[pinned]},pinned.region,'medium_3_0').dockerVersion,pinned.dockerVersion);
 const provider={...snapshot(),tags};assert.equal(verifyHostSnapshot(pinned,provider),pinned);
 assert.throws(()=>verifyHostSnapshot({...pinned,dockerVersion:pinned.dockerVersion.replace('~','-')},provider));
 provider.tags=tags.map(t=>t.key==='canopy-docker-version'?{...t,value:t.value+'tampered'}:t);assert.throws(()=>verifyHostSnapshot(pinned,provider));
});
test('active code updates reuse only the declared matching base dependency lock',()=>{const catalog={version:1,entries:[record]},next='f'.repeat(64);assert.equal(selectHostSnapshot(catalog,record.region,'medium_3_0',next,record.lockSha256),record);for(const lock of [undefined,'e'.repeat(64),'bad'])assert.throws(()=>selectHostSnapshot(catalog,record.region,'medium_3_0',next,lock));const changed=snapshot();changed.tags=changed.tags.map(tag=>tag.key==='canopy-runtime-sha256'?{...tag,value:next}:tag);assert.throws(()=>verifyHostSnapshot(record,changed));});
test('the 16 vCPU / 64 GB package is a valid snapshot target',()=>{const big={...record,targetBundles:[...record.targetBundles,'4xlarge_3_0']};assert.equal(selectHostSnapshot({version:1,entries:[big]},big.region,'4xlarge_3_0'),big);assert.throws(()=>selectHostSnapshot({version:1,entries:[{...record,targetBundles:['8xlarge_3_0']}]},record.region,'8xlarge_3_0'),/not verified/);});
