const escapeHtml=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
export function invitationEmail({inviter,email,url,kind='organization'}){
 const link=new URL(url);if(!['http:','https:'].includes(link.protocol)||link.username||link.password)throw Error('Invalid invitation URL');
 if(!['organization','team'].includes(kind))throw Error('Invalid invitation type');
 const subject=`You’re invited to join a Canopy ${kind}`;
 const intro=`${inviter} invited you to join their ${kind} on Canopy.`;
 const details=`Sign in with ${email} to review and accept this invitation. Your workspace access will be shown after you join.`;
 const expiry='This invitation expires in seven days. If you weren’t expecting it, you can ignore this email.';
 const text=`CANOPY\n\nYou’re invited\n\n${intro}\n\n${details}\n\nReview invitation:\n${link.href}\n\n${expiry}\n\nThe Canopy team\nhttps://canopyide.dev\n`;
 const safe=escapeHtml(link.href);
 const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(subject)}</title></head><body style="margin:0;background:#f4f5f0;color:#1c211a;font-family:Arial,Helvetica,sans-serif"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td align="center" style="padding:40px 16px"><table role="presentation" width="560" cellspacing="0" cellpadding="0" style="width:100%;max-width:560px;background:white;border:1px solid #dce0d5;border-radius:12px"><tr><td style="padding:28px 32px;border-bottom:1px solid #e6e8e1;font-size:24px;font-weight:bold">canopy<span style="color:#648000">.</span></td></tr><tr><td style="padding:32px"><h1 style="margin:0 0 20px;font-size:28px">You’re invited</h1><p style="font-size:16px;line-height:1.7;margin:0 0 16px">${escapeHtml(intro)}</p><p style="font-size:16px;line-height:1.7;margin:0 0 28px">Sign in with <strong>${escapeHtml(email)}</strong> to review and accept this invitation.</p><a href="${safe}" style="display:inline-block;background:#d4f750;border:1px solid #a5c333;border-radius:6px;padding:15px 24px;color:#172006;text-decoration:none;font-size:16px;font-weight:bold">Review invitation &rarr;</a><p style="font-size:14px;line-height:1.7;color:#555f4e;margin:24px 0">Your workspace access will be shown after you join.</p><p style="font-size:14px;line-height:1.7;color:#555f4e">${escapeHtml(expiry)}</p><p style="margin:24px 0 0;font-size:15px">The Canopy team</p></td></tr><tr><td style="padding:24px 32px;border-top:1px solid #e6e8e1;font-size:12px;line-height:1.7;color:#68715f">Button not working? Copy this link into your browser:<br><a href="${safe}" style="color:#4c6500;overflow-wrap:anywhere;word-break:break-all">${safe}</a></td></tr></table><p style="font-size:12px;color:#68715f;margin:24px 0">Canopy · Your workspace for building with your own agents</p></td></tr></table></body></html>`;
 return {subject,text,html};
}
