import test from 'node:test';import assert from 'node:assert/strict';import {requestMemberResume,advanceMemberResume,memberResumeKey,canResumeShared} from './member-resume.mjs';import {requestOperation} from './lifecycle.mjs';
const requestKey='11111111-1111-4111-8111-111111111111',base={id:'ws-shared',owner_id:'owner',organization_id:null,provider:'lightsail',generation:4,sharing_generation:3,state:'stopped',desired_state:'stopped',plan_id:'owner-plan'};
function fixture({workspace=structuredClone(base),grants=[{role:'member',permissions:{projects:'selected',projectIds:['app']}}],latest=null,organizationMember=true}={}){
 const queries=[],operations=new Map();let currentLatest=latest;const db={query:async(sql,args=[])=>{
  queries.push([sql,args]);if(sql.startsWith('SELECT * FROM workspace WHERE'))return {rows:args[1]===workspace.owner_id?[workspace]:[]};if(sql.startsWith('SELECT owner_id'))return {rows:[workspace]};if(sql.includes('FROM organization_member'))return {rows:organizationMember?[{joined_at:'current'}]:[]};if(sql.includes('FROM workspace_member'))return {rows:grants};if(sql.includes('FROM workspace_team_access'))return {rows:[]};
  if(sql.startsWith('SELECT id,workspace_id'))return {rows:currentLatest?[currentLatest]:[]};if(sql.includes('pg_try_advisory_xact_lock'))return {rows:[{acquired:true}]};if(sql.startsWith('SELECT * FROM workspace_operation WHERE id='))return {rows:currentLatest?[currentLatest]:[]};if(sql.startsWith('SELECT * FROM workspace_operation'))return {rows:operations.has(args[1])?[operations.get(args[1])]:[]};if(sql.startsWith('SELECT id FROM workspace_operation'))return {rows:[]};if(sql.startsWith('UPDATE workspace SET generation')){workspace.generation++;workspace.desired_state=args[1];return {rows:[{generation:workspace.generation}]};}
  if(sql.startsWith('UPDATE workspace_operation')){assert.ok(sql.includes("context=(context-'phaseStartedAt'-'bootstrapReport')"));delete currentLatest.context.phaseStartedAt;delete currentLatest.context.bootstrapReport;currentLatest.status='pending';currentLatest.context={...currentLatest.context,...JSON.parse(args[1])};return {rows:[currentLatest]};}
  if(sql.startsWith('INSERT INTO workspace_operation')){const [workspace_id,owner_id,key,action,generation,target_plan_id,context]=args,op={id:'op',workspace_id,owner_id,request_key:key,action,generation,target_plan_id,context:JSON.parse(context),status:'pending',phase:'queued'};operations.set(key,op);return {rows:[op]};}throw Error('Unexpected SQL '+sql);
 }};return {db,queries,workspace,operations};
}
test('guest resume is owner-funded, requester-audited and strips plan/owner/context overrides',async()=>{
 const f=fixture();const op=await requestMemberResume(f.db,'alice',f.workspace,{action:'resume',requestKey,planId:'expensive',owner_id:'alice',context:{requesterId:'owner'},generation:99});assert.equal(op.owner_id,'owner');assert.equal(op.target_plan_id,null);assert.equal(op.context.requesterId,'alice');assert.equal(op.context.previousPlanId,'owner-plan');assert.equal(op.request_key,memberResumeKey(base.id,'alice',requestKey));assert.equal(f.workspace.generation,5);
 const replay=await requestMemberResume(f.db,'alice',f.workspace,{action:'resume',requestKey,planId:'other'});assert.equal(replay.id,op.id);assert.equal(f.workspace.generation,5);assert.notEqual(memberResumeKey(base.id,'bob',requestKey),op.request_key);
});
test('viewer, empty developer policy, removed organization and initial unverified sharing cannot wake compute',async()=>{
 for(const options of [{grants:[{role:'viewer',permissions:{projects:'all'}}]},{grants:[{role:'viewer',permissions:{projects:'all'}},{role:'member',permissions:{projects:'selected',projectIds:[]}}]},{workspace:{...base,sharing_generation:null}},{workspace:{...base,organization_id:'org'},organizationMember:false},{workspace:{...base,desired_state:'deleted'}}]){
  const f=fixture(options);await assert.rejects(requestMemberResume(f.db,'alice',f.workspace,{action:'resume',requestKey}),/cannot resume/);assert.ok(!f.queries.some(([sql])=>sql.startsWith('UPDATE')||sql.startsWith('INSERT')));
 }
});
test('only explicit resume and existing owner-funded resume operations are exposed to guests',async()=>{
 const f=fixture();for(const action of ['delete','hibernate','resize','retry','billing'])await assert.rejects(requestMemberResume(f.db,'alice',f.workspace,{action,requestKey}),/Only shared workspace resume/);assert.equal(f.queries.length,0);
 const resumed=fixture({workspace:{...base,state:'starting',desired_state:'running'},latest:{id:'resume',workspace_id:base.id,owner_id:'owner',action:'resume',status:'running'}});assert.equal((await advanceMemberResume(resumed.db,'alice',resumed.workspace)).id,'resume');
 for(const action of ['delete','resize','hibernate']){const changed=fixture({latest:{id:'op',workspace_id:base.id,owner_id:'owner',action,status:'running'}});await assert.rejects(advanceMemberResume(changed.db,'alice',changed.workspace));assert.ok(!changed.queries.some(([sql])=>sql.startsWith('UPDATE')||sql.startsWith('INSERT')));}
});
test('already ready resume is a no-op and does not change generation or add billable operations',async()=>{
 const f=fixture({workspace:{...base,state:'ready',desired_state:'running',sharing_generation:4}});const result=await requestMemberResume(f.db,'alice',f.workspace,{action:'resume',requestKey});assert.equal(result.noop,true);assert.equal(f.workspace.generation,4);assert.equal(f.operations.size,0);assert.equal((await advanceMemberResume(f.db,'alice',f.workspace)).noop,true);
 const owner=fixture({workspace:{...base,state:'ready',desired_state:'running'}});assert.equal((await requestOperation(owner.db,'owner',owner.workspace.id,{action:'resume',requestKey})).noop,true);assert.equal(owner.workspace.generation,4);
});
test('resume visibility accepts narrow writable grants without granting unrelated project or infrastructure controls',()=>{
 assert.equal(canResumeShared(base,[{role:'viewer',permissions:{projects:'all'}},{role:'member',permissions:{projects:'selected',projectIds:['app']}}]),true);assert.equal(canResumeShared(base,[{role:'member',permissions:{projects:'selected',projectIds:[]}}]),false);assert.equal(canResumeShared(base,[{role:'member',permissions:{projects:'all'}}],{action:'resize',status:'failed'}),false);
});
test('guest retry preserves failed resume generation/context and records actor-bound retry without changing the compute plan',async()=>{
 const failed={id:'failed',workspace_id:base.id,owner_id:'owner',action:'resume',status:'failed',generation:4,phase:'attach-storage',context:{requesterId:'owner',instanceName:'original-partial-instance',diskName:'retained-disk',phaseStartedAt:'old',bootstrapReport:{status:'failed',stage:'image',sequence:3}}};const f=fixture({workspace:{...base,state:'error',desired_state:'running'},latest:failed});
 const retried=await requestMemberResume(f.db,'alice',f.workspace,{action:'resume',requestKey,planId:'expensive'});assert.equal(retried.generation,4);assert.equal(retried.phase,'attach-storage');assert.equal(retried.context.requesterId,'owner');assert.equal(retried.context.retryRequesterId,'alice');assert.equal(retried.context.retryRequestKey,memberResumeKey(base.id,'alice',requestKey));assert.equal(retried.context.instanceName,'original-partial-instance');assert.equal(retried.context.diskName,'retained-disk');assert.equal(retried.context.bootstrapReport,undefined);assert.equal(retried.context.phaseStartedAt,undefined);assert.equal(f.workspace.generation,4);assert.equal(f.operations.size,0);
 const updates=f.queries.filter(([sql])=>sql.startsWith('UPDATE workspace_operation')).length;await requestMemberResume(f.db,'alice',f.workspace,{action:'resume',requestKey});assert.equal(f.queries.filter(([sql])=>sql.startsWith('UPDATE workspace_operation')).length,updates);assert.equal(memberResumeKey(base.id,'alice',requestKey.toUpperCase()),memberResumeKey(base.id,'alice',requestKey));
});
