import test from 'node:test';import assert from 'node:assert/strict';import {constants} from 'node:fs';
import {adoptRetainedManagementOwner} from './retained-bootstrap-owner.mjs';
function fixture(){const calls=[],bytes=JSON.stringify({workspaceId:'synthetic',projects:['app'],key:'synthetic-only'}),input={workspaceId:'synthetic',generation:9};let absent=false,link=false,swap=false;
 const directory=(fd,uid,mode)=>({fd,info:{uid,mode,isDirectory:()=>true},stat:async function(){return this.info;},chown:async function(uid,gid){calls.push(['chown-dir',fd,uid,gid]);this.info.uid=uid;},sync:async()=>{},close:async()=>{}});
 const srv=directory(1,0,0o755),mount=directory(2,0,0o755),dir=directory(3,995,0o700),file={fd:4,info:{uid:995,mode:0o600,nlink:1,size:bytes.length,dev:1,ino:44,isFile:()=>true},stat:async function(){return this.info;},readFile:async()=>bytes,chown:async function(uid,gid){calls.push(['chown-file',uid,gid]);this.info.uid=uid;},sync:async()=>{},close:async()=>{}};
 const open=async(path,flags)=>{calls.push(['open',path,flags]);assert.ok(flags&constants.O_NOFOLLOW);if(path==='/srv')return srv;if(path==='/proc/self/fd/1/canopy')return mount;if(path==='/proc/self/fd/2/host-state')return dir;if(path==='/proc/self/fd/3/host-config.json'){if(link)throw Object.assign(Error('symlink'),{code:'ELOOP'});if(absent)throw Object.assign(Error('missing'),{code:'ENOENT'});return swap&&calls.some(c=>c[0]==='chown-file')?{...file,stat:async()=>({...file.info,ino:99})}:file;}throw Error('Unexpected path');};
 const merge=(incoming,retained)=>{calls.push(['validate']);if(incoming.workspaceId!==retained.workspaceId)throw Error('Retained workspace identity differs');};
 return {calls,srv,mount,dir,file,input,options:{open,constants,merge,incoming:input},missing:()=>{absent=true;},symlink:()=>{link=true;},swap:()=>{swap=true;}};
}
test('legitimate prior service ownership is adopted only after identity validation, preserving all bytes',async()=>{const f=fixture();const before=await f.file.readFile();await adoptRetainedManagementOwner(f.options);assert.equal(f.dir.info.uid,0);assert.equal(f.file.info.uid,0);assert.equal(await f.file.readFile(),before);assert.ok(f.calls.findIndex(c=>c[0]==='validate')<f.calls.findIndex(c=>c[0]==='chown-dir'));assert.deepEqual(f.calls.filter(c=>c[0].startsWith('chown')), [['chown-dir',3,0,0],['chown-file',0,0]]);});
test('public metadata, regular-user ownership, hardlinks, oversized files and foreign identity fail before chown',async()=>{for(const change of [f=>f.srv.info.uid=1000,f=>f.mount.info.mode=0o777,f=>f.dir.info.mode=0o755,f=>f.dir.info.uid=1000,f=>f.file.info.mode=0o644,f=>f.file.info.uid=1000,f=>f.file.info.uid=996,f=>f.file.readFile=async()=>'{broken',f=>f.options.merge=()=>{throw Error('Invalid retained schema');},f=>f.file.info.nlink=2,f=>f.file.info.size=1024*1024+1,f=>f.input.workspaceId='foreign',f=>f.symlink()]){const f=fixture();change(f);await assert.rejects(adoptRetainedManagementOwner(f.options));assert.equal(f.calls.some(c=>c[0].startsWith('chown')),false);}});
test('file replacement is detected before strict merge can read it; missing configuration never touches user data',async()=>{const replaced=fixture();replaced.swap();await assert.rejects(adoptRetainedManagementOwner(replaced.options),/Unsafe/);const missing=fixture();missing.missing();await adoptRetainedManagementOwner(missing.options);assert.deepEqual(missing.calls.filter(c=>c[0].startsWith('chown')),[['chown-dir',3,0,0]]);assert.ok(missing.calls.every(c=>c[0]!=='open'||!c[1].includes('/projects/')));});

test('a partial root-directory adoption or private legacy copy remains retryable without accepting regular-user ownership',async()=>{const partial=fixture();partial.dir.info.uid=0;await adoptRetainedManagementOwner(partial.options);assert.equal(partial.file.info.uid,0);const foreign=fixture();foreign.dir.info.uid=0;foreign.file.info.uid=1000;await assert.rejects(adoptRetainedManagementOwner(foreign.options));assert.equal(foreign.calls.some(c=>c[0].startsWith('chown')),false);});
