import test from 'node:test';import assert from 'node:assert/strict';import {createHmac} from 'node:crypto';
import {verifySharingProof,activateWorkspaceSharing} from './sharing-activation.mjs';
const key='synthetic-management-key-32-bytes',now=100000,expected={workspaceId:'ws-test',generation:3,instanceName:'machine',nonce:'a'.repeat(64)};
const claims=()=>({version:1,purpose:'sharing-ready',...expected,catalogHash:'b'.repeat(64),expiresAt:now+30000});
const sign=value=>{const p=Buffer.from(JSON.stringify(value)).toString('base64url');return p+'.'+createHmac('sha256',key).update(p).digest('base64url');};
test('readiness proof binds host, generation, workspace and fresh server nonce',()=>{assert.equal(verifySharingProof(sign(claims()),key,expected,now).generation,3);for(const field of ['workspaceId','generation','instanceName','nonce'])assert.throws(()=>verifySharingProof(sign(claims()),key,{...expected,[field]:'different'},now));assert.throws(()=>verifySharingProof(sign(claims()),key,expected,now+30000));assert.throws(()=>verifySharingProof(sign({...claims(),extra:true}),key,expected,now));assert.throws(()=>verifySharingProof(sign(claims())+'x',key,expected,now));});
function fixture(){let updates=0,requests=0;const workspace={id:'ws-test',owner_id:'owner',generation:3,provider:'lightsail',state:'ready',desired_state:'running',endpoint:'https://workspace.example',instance_name:'machine'};
 const options={key,token:'synthetic-owner-token',expectedEndpoint:workspace.endpoint,now:()=>now,nonce:()=>expected.nonce,provider:{instance:async()=>({name:'machine',state:{name:'running'},tags:[{key:'canopy-workspace',value:'ws-test'},{key:'managed-by',value:'canopy'}]})},request:async(url,request)=>{requests++;assert.equal(url,'https://workspace.example/v1/workspaces/ws-test/sharing-setup');assert.equal(JSON.parse(request.body).nonce,expected.nonce);return {ok:true,headers:{get:()=>expected.instanceName},json:async()=>({proof:sign(claims()),projects:[{id:'app',name:'Product',components:[{id:'api',name:'API'}],privatePath:'/private',secret:'discard'}]})};}};
 const db={query:async(sql,values)=>{updates++;assert.match(sql,/generation=\$2/);assert.deepEqual(values,['ws-test',3,'owner','machine','https://workspace.example']);return {rows:[{id:'ws-test'}]};}};
 return {workspace,options,db,counts:()=>({updates,requests})};}
test('activation uses provider identity and management proof before CAS; response strips private fields',async()=>{const f=fixture();const result=await activateWorkspaceSharing(f.db,'owner',f.workspace,f.options);assert.deepEqual(result.projects,[{id:'app',name:'Product',components:[{id:'api',name:'API'}]}]);assert.deepEqual(f.counts(),{updates:1,requests:1});});
test('outsiders, shutdown, foreign endpoints and foreign machines cannot request or activate sharing',async()=>{for(const mutate of [f=>f.workspace.owner_id='other',f=>f.workspace.desired_state='stopped',f=>f.workspace.endpoint='https://foreign.example',f=>f.options.provider.instance=async()=>({name:'foreign'})]){const f=fixture();mutate(f);await assert.rejects(activateWorkspaceSharing(f.db,'owner',f.workspace,f.options));assert.deepEqual(f.counts(),{updates:0,requests:0});}});
test('changed machine generation during activation rejects publication',async()=>{const f=fixture();f.db.query=async()=>({rows:[]});await assert.rejects(activateWorkspaceSharing(f.db,'owner',f.workspace,f.options),/changed/);});
