import test from 'node:test';import assert from 'node:assert/strict';import {createHmac} from 'node:crypto';import {trustedWorkspaceIdle} from './workspace-idle.mjs';
const key='synthetic-host-key-for-test-only-32',nonce='a'.repeat(64),now=100000;
const w={id:'ws-test',provider:'lightsail',state:'ready',desired_state:'running',generation:2,instance_name:'machine',endpoint:'https://workspace.example'};
const sign=c=>{const payload=Buffer.from(JSON.stringify(c)).toString('base64url');return payload+'.'+createHmac('sha256',key).update(payload).digest('base64url');};
function fixture(){const c={version:1,purpose:'workspace-idle',workspaceId:w.id,generation:2,instanceName:'machine',nonce,idle:true,expiresAt:now+30000};let requests=0;const db={query:async()=>({rows:[]})};const options={key,token:'synthetic',nonce:()=>nonce,now:()=>now,expectedEndpoint:w.endpoint,provider:{instance:async()=>({name:'machine',state:{name:'running'},tags:[{key:'canopy-workspace',value:w.id},{key:'managed-by',value:'canopy'}]})},request:async()=>{requests++;return {ok:true,headers:{get:()=>w.instance_name},json:async()=>({idle:true,proof:sign(c)})};}};return {c,db,options,requests:()=>requests};}
test('only provider-confirmed, lease-free, signed management idle proof permits shutdown',async()=>{const f=fixture();assert.deepEqual(await trustedWorkspaceIdle(f.db,w,f.options),{accepted:true});});
test('any active IDE lease prevents an idle request including another member',async()=>{const f=fixture();f.db.query=async()=>({rows:[{}]});assert.equal((await trustedWorkspaceIdle(f.db,w,f.options)).accepted,false);assert.equal(f.requests(),0);});
test('fabricated user activity, changed identity, stale nonce and sharing-purpose proof cannot stop compute',async()=>{for(const change of [c=>c.purpose='sharing-ready',c=>c.generation=3,c=>c.workspaceId='other',c=>c.instanceName='other',c=>c.nonce='b'.repeat(64),c=>c.expiresAt=now,c=>c.idle=false]){const f=fixture();change(f.c);assert.equal((await trustedWorkspaceIdle(f.db,w,f.options)).accepted,false);}const f=fixture();f.options.request=async()=>({ok:true,headers:{get:()=>w.instance_name},json:async()=>({idle:true,activeAgents:0,activeJobs:0,sampledAt:now})});assert.equal((await trustedWorkspaceIdle(f.db,w,f.options)).accepted,false);});
test('intentional shutdown and foreign provider identity deny automatic shutdown',async()=>{const f=fixture();assert.equal((await trustedWorkspaceIdle(f.db,{...w,desired_state:'stopped'},f.options)).accepted,false);f.options.provider.instance=async()=>null;assert.equal((await trustedWorkspaceIdle(f.db,w,f.options)).accepted,false);});
